/* eslint-disable @typescript-eslint/no-explicit-any */
import { StorageInfo, StorageLoad } from '@dash/common';
import * as si from 'systeminformation';

export type TestCase = {
  disks: si.Systeminformation.DiskLayoutData[];
  blocks: si.Systeminformation.BlockDevicesData[];
  sizes: si.Systeminformation.FsSizeData[];
  layout: StorageInfo;
  output: StorageLoad;
};

// https://github.com/MauriceNino/dashdot/issues/514
export const TEST_CASE_14 = {
  disks: [
    {
      device: '/dev/nvme0n1',
      type: 'NVMe',
      name: 'SAMSUNG MZVL2512HCJQ-00B00              ',
      vendor: 'Samsung',
      size: 512110190592,
      bytesPerSector: null,
      totalCylinders: null,
      totalHeads: null,
      totalSectors: null,
      totalTracks: null,
      tracksPerCylinder: null,
      sectorsPerTrack: null,
      firmwareRevision: '',
      serialNum: 'S675NX0T349018',
      interfaceType: 'PCIe',
      smartStatus: 'unknown',
      temperature: null,
    },
    {
      device: '/dev/nvme1n1',
      type: 'NVMe',
      name: 'SAMSUNG MZVL2512HCJQ-00B00              ',
      vendor: 'Samsung',
      size: 512110190592,
      bytesPerSector: null,
      totalCylinders: null,
      totalHeads: null,
      totalSectors: null,
      totalTracks: null,
      tracksPerCylinder: null,
      sectorsPerTrack: null,
      firmwareRevision: '',
      serialNum: 'S675NX0T551801',
      interfaceType: 'PCIe',
      smartStatus: 'unknown',
      temperature: null,
    },
  ],
  sizes: [
    {
      fs: 'overlay',
      type: 'overlay',
      size: 467645579264,
      used: 322657038336,
      available: 121158221824,
      use: 72.7,
      mount: '/',
      rw: false,
    },
    {
      fs: '/dev/md3',
      type: 'ext4',
      size: 467645579264,
      used: 322657038336,
      available: 121158221824,
      use: 72.7,
      mount: '/mnt/host',
      rw: true,
    },
    {
      fs: '/dev/md2',
      type: 'ext3',
      size: 1036726272,
      used: 126164992,
      available: 856981504,
      use: 12.83,
      mount: '/mnt/host/boot',
      rw: true,
    },
    {
      fs: '/dev/md0',
      type: 'vfat',
      size: 268087296,
      used: 176128,
      available: 267911168,
      use: 0.07,
      mount: '/mnt/host/boot/efi',
      rw: true,
    },
    {
      fs: 'db-ita-crypt:/',
      type: 'fuse.rclone',
      size: 1845410008137728,
      used: 1374804697473024,
      available: 470605310664704,
      use: 74.5,
      mount: '/mnt/host/media',
      rw: false,
    },
  ],
  blocks: [
    {
      name: 'nvme0n1',
      type: 'disk',
      fsType: '',
      mount: '',
      size: 512110190592,
      physical: 'SSD',
      uuid: '',
      label: '',
      model: 'SAMSUNG MZVL2512HCJQ-00B00',
      serial: 'S675NX0T349018      ',
      removable: false,
      protocol: 'nvme',
      group: '',
      device: '/dev/nvme0n1',
    },
    {
      name: 'nvme1n1',
      type: 'disk',
      fsType: '',
      mount: '',
      size: 512110190592,
      physical: 'SSD',
      uuid: '',
      label: '',
      model: 'SAMSUNG MZVL2512HCJQ-00B00',
      serial: 'S675NX0T551801      ',
      removable: false,
      protocol: 'nvme',
      group: '',
      device: '/dev/nvme1n1',
    },
    {
      name: 'nvme0n1p1',
      type: 'part',
      fsType: 'linux_raid_member',
      mount: '',
      size: 268435456,
      physical: '',
      uuid: '8df5997d-5c07-5336-7809-e1c1d275f2fe',
      label: 'archlinux-latest-64-minimal:0',
      model: '',
      serial: '',
      removable: false,
      protocol: 'nvme',
      group: 'md0',
      device: '/dev/nvme0n1',
    },
    {
      name: 'nvme0n1p2',
      type: 'part',
      fsType: 'linux_raid_member',
      mount: '',
      size: 34359738368,
      physical: '',
      uuid: '0a811c0a-841f-c9d2-8a5c-4f39e3c91f82',
      label: 'archlinux-latest-64-minimal:1',
      model: '',
      serial: '',
      removable: false,
      protocol: 'nvme',
      group: 'md1',
      device: '/dev/nvme0n1',
    },
    {
      name: 'nvme0n1p3',
      type: 'part',
      fsType: 'linux_raid_member',
      mount: '',
      size: 1073741824,
      physical: '',
      uuid: 'cf2c6311-172d-a71c-0b49-2b2deb8a7be5',
      label: 'archlinux-latest-64-minimal:2',
      model: '',
      serial: '',
      removable: false,
      protocol: 'nvme',
      group: 'md2',
      device: '/dev/nvme0n1',
    },
    {
      name: 'nvme0n1p4',
      type: 'part',
      fsType: 'linux_raid_member',
      mount: '',
      size: 476406160896,
      physical: '',
      uuid: '7b8fc46e-10f1-612a-84a6-e6411f4dcaca',
      label: 'archlinux-latest-64-minimal:3',
      model: '',
      serial: '',
      removable: false,
      protocol: 'nvme',
      group: 'md3',
      device: '/dev/nvme0n1',
    },
    {
      name: 'nvme1n1p1',
      type: 'part',
      fsType: 'linux_raid_member',
      mount: '',
      size: 268435456,
      physical: '',
      uuid: '8df5997d-5c07-5336-7809-e1c1d275f2fe',
      label: 'archlinux-latest-64-minimal:0',
      model: '',
      serial: '',
      removable: false,
      protocol: 'nvme',
      group: 'md0',
      device: '/dev/nvme1n1',
    },
    {
      name: 'nvme1n1p2',
      type: 'part',
      fsType: 'linux_raid_member',
      mount: '',
      size: 34359738368,
      physical: '',
      uuid: '0a811c0a-841f-c9d2-8a5c-4f39e3c91f82',
      label: 'archlinux-latest-64-minimal:1',
      model: '',
      serial: '',
      removable: false,
      protocol: 'nvme',
      group: 'md1',
      device: '/dev/nvme1n1',
    },
    {
      name: 'nvme1n1p3',
      type: 'part',
      fsType: 'linux_raid_member',
      mount: '',
      size: 1073741824,
      physical: '',
      uuid: 'cf2c6311-172d-a71c-0b49-2b2deb8a7be5',
      label: 'archlinux-latest-64-minimal:2',
      model: '',
      serial: '',
      removable: false,
      protocol: 'nvme',
      group: 'md2',
      device: '/dev/nvme1n1',
    },
    {
      name: 'nvme1n1p4',
      type: 'part',
      fsType: 'linux_raid_member',
      mount: '',
      size: 476406160896,
      physical: '',
      uuid: '7b8fc46e-10f1-612a-84a6-e6411f4dcaca',
      label: 'archlinux-latest-64-minimal:3',
      model: '',
      serial: '',
      removable: false,
      protocol: 'nvme',
      group: 'md3',
      device: '/dev/nvme1n1',
    },
    {
      name: 'md0',
      type: 'raid1',
      fsType: 'vfat',
      mount: '/mnt/host/boot/efi',
      size: 268369920,
      physical: '',
      uuid: 'F539-5EE9',
      label: 'archlinux-latest-64-minimal:0',
      model: '',
      serial: '',
      removable: false,
      protocol: '',
      group: '',
    },
    {
      name: 'md1',
      type: 'raid1',
      fsType: 'swap',
      mount: '[SWAP]',
      size: 34325135360,
      physical: '',
      uuid: '3cd6a192-5778-48af-bfb1-8e30da09122e',
      label: 'archlinux-latest-64-minimal:1',
      model: '',
      serial: '',
      removable: false,
      protocol: '',
      group: '',
    },
    {
      name: 'md2',
      type: 'raid1',
      fsType: 'ext3',
      mount: '/mnt/host/boot',
      size: 1071644672,
      physical: '',
      uuid: '53300eed-6ccb-4ad7-878f-9359a47fddac',
      label: 'archlinux-latest-64-minimal:2',
      model: '',
      serial: '',
      removable: false,
      protocol: '',
      group: '',
    },
    {
      name: 'md3',
      type: 'raid1',
      fsType: 'ext4',
      mount: '/mnt/host',
      size: 476270886912,
      physical: '',
      uuid: '826abd28-f0af-4b95-8e27-34ce300b1304',
      label: 'archlinux-latest-64-minimal:3',
      model: '',
      serial: '',
      removable: false,
      protocol: '',
      group: '',
    },
  ],
  layout: [
    {
      disks: [
        { brand: 'Samsung', device: 'nvme0n1', type: 'NVMe' },
        { brand: 'Samsung', device: 'nvme1n1', type: 'NVMe' },
      ],
      raidLabel: 'archlinux-latest-64-minimal',
      raidName: 'md0',
      raidType: 1,
      size: 511936036864,
    },
  ],
  output: [365769023488],
} as any as TestCase;

export const TEST_CASE_15 = {
  disks: [
    {
      device: '\\\\.\\PHYSICALDRIVE0',
      type: 'HD',
      name: 'ST8000DM004-2CX188',
      vendor: 'Seagate',
      size: 8001560609280,
      bytesPerSector: 512,
      totalCylinders: 972801,
      totalHeads: 255,
      totalSectors: 15628048065,
      totalTracks: 248064255,
      tracksPerCylinder: 255,
      sectorsPerTrack: 63,
      firmwareRevision: '0001',
      serialNum: 'ZCT35GKB',
      interfaceType: 'SATA',
      smartStatus: 'Ok',
      temperature: null,
    },
    {
      device: '\\\\.\\PHYSICALDRIVE1',
      type: 'SSD',
      name: 'TS256GSSD370',
      vendor: '',
      size: 256052966400,
      bytesPerSector: 512,
      totalCylinders: 31130,
      totalHeads: 255,
      totalSectors: 500103450,
      totalTracks: 7938150,
      tracksPerCylinder: 255,
      sectorsPerTrack: 63,
      firmwareRevision: '20140516',
      serialNum: 'B669542640',
      interfaceType: 'SATA',
      smartStatus: 'Ok',
      temperature: null,
    },
  ],
  sizes: [
    {
      fs: 'A:',
      type: 'NTFS',
      size: 537915392,
      used: 449269760,
      available: 88645632,
      use: 83.52,
      mount: 'A:',
      rw: true,
    },
    {
      fs: 'C:',
      type: 'NTFS',
      size: 254874218496,
      used: 225739960320,
      available: 29134258176,
      use: 88.57,
      mount: 'C:',
      rw: true,
    },
    {
      fs: 'E:',
      type: 'NTFS',
      size: 8001545039872,
      used: 7547945865216,
      available: 453599174656,
      use: 94.33,
      mount: 'E:',
      rw: true,
    },
  ],
  blocks: [
    {
      name: 'A:',
      identifier: 'A:',
      type: 'disk',
      fsType: 'ntfs',
      mount: 'A:',
      size: '537915392',
      physical: 'Local',
      uuid: '860E0ABE',
      label: '',
      model: '',
      serial: '860E0ABE',
      removable: false,
      protocol: '',
      group: '',
      device: '\\\\.\\PHYSICALDRIVE1',
    },
    {
      name: 'C:',
      identifier: 'C:',
      type: 'disk',
      fsType: 'ntfs',
      mount: 'C:',
      size: '254874218496',
      physical: 'Local',
      uuid: '02712ECC',
      label: '',
      model: '',
      serial: '02712ECC',
      removable: false,
      protocol: '',
      group: '',
      device: '\\\\.\\PHYSICALDRIVE1',
    },
    {
      name: 'D:',
      identifier: 'D:',
      type: 'disk',
      fsType: 'cdfs',
      mount: 'D:',
      size: '0',
      physical: 'CD/DVD',
      uuid: '00B500CD',
      label: 'Audio CD',
      model: '',
      serial: '00B500CD',
      removable: false,
      protocol: '',
      group: '',
      device: '',
    },
    {
      name: 'E:',
      identifier: 'E:',
      type: 'disk',
      fsType: 'ntfs',
      mount: 'E:',
      size: '8001545039872',
      physical: 'Local',
      uuid: '2EF6177C',
      label: 'Media',
      model: '',
      serial: '2EF6177C',
      removable: false,
      protocol: '',
      group: '',
      device: '\\\\.\\PHYSICALDRIVE0',
    },
  ],
  layout: [
    {
      disks: [{ brand: '', device: '\\\\.\\PHYSICALDRIVE1', type: 'SSD' }],
      size: 256052966400,
    },
    {
      disks: [
        { brand: 'Seagate', device: '\\\\.\\PHYSICALDRIVE0', type: 'HD' },
      ],
      size: 8001560609280,
    },
  ],
  output: [226830062592, 7547961434624],
} as any as TestCase;

export const TEST_CASE_16 = {
  disks: [
    {
      device: '\\\\.\\PHYSICALDRIVE1',
      type: 'SSD',
      name: 'Samsung SSD 980 1TB',
      vendor: 'Samsung',
      size: 1000202273280,
      bytesPerSector: 512,
      totalCylinders: 121601,
      totalHeads: 255,
      totalSectors: 1953520065,
      totalTracks: 31008255,
      tracksPerCylinder: 255,
      sectorsPerTrack: 63,
      firmwareRevision: '2B4QFXO7',
      serialNum: '0025_38D1_21B1_C5DF.',
      interfaceType: 'NVMe',
      smartStatus: 'Ok',
      temperature: null,
    },
    {
      device: '\\\\.\\PHYSICALDRIVE2',
      type: 'SSD',
      name: 'Samsung SSD 970 EVO Plus 500GB',
      vendor: 'Samsung',
      size: 500105249280,
      bytesPerSector: 512,
      totalCylinders: 60801,
      totalHeads: 255,
      totalSectors: 976768065,
      totalTracks: 15504255,
      tracksPerCylinder: 255,
      sectorsPerTrack: 63,
      firmwareRevision: '2B2QEXM7',
      serialNum: '0025_3854_0140_5BFA.',
      interfaceType: 'NVMe',
      smartStatus: 'Ok',
      temperature: null,
    },
    {
      device: '\\\\.\\PHYSICALDRIVE0',
      type: 'SSD',
      name: 'Samsung SSD 860 EVO 1TB',
      vendor: 'Samsung',
      size: 1000202273280,
      bytesPerSector: 512,
      totalCylinders: 121601,
      totalHeads: 255,
      totalSectors: 1953520065,
      totalTracks: 31008255,
      tracksPerCylinder: 255,
      sectorsPerTrack: 63,
      firmwareRevision: 'RVT04B6Q',
      serialNum: 'S4CSNJ0NB02348Z',
      interfaceType: 'SATA',
      smartStatus: 'Ok',
      temperature: null,
    },
  ],
  sizes: [
    {
      fs: 'C:',
      type: 'NTFS',
      size: 499328741376,
      used: 177384513536,
      available: 321944227840,
      use: 35.52,
      mount: 'C:',
      rw: true,
    },
    {
      fs: 'D:',
      type: 'NTFS',
      size: 1000186310656,
      used: 880458645504,
      available: 119727665152,
      use: 88.03,
      mount: 'D:',
      rw: true,
    },
    {
      fs: 'E:',
      type: 'NTFS',
      size: 1000202039296,
      used: 606456291328,
      available: 393745747968,
      use: 60.63,
      mount: 'E:',
      rw: true,
    },
  ],
  blocks: [
    {
      name: 'C:',
      identifier: 'C:',
      type: 'disk',
      fsType: 'ntfs',
      mount: 'C:',
      size: '499328741376',
      physical: 'Local',
      uuid: '02887811',
      label: '',
      model: '',
      serial: '02887811',
      removable: false,
      protocol: '',
      group: '',
      device: '\\\\.\\PHYSICALDRIVE2',
    },
    {
      name: 'D:',
      identifier: 'D:',
      type: 'disk',
      fsType: 'ntfs',
      mount: 'D:',
      size: '1000186310656',
      physical: 'Local',
      uuid: '2A7043B9',
      label: 'Data',
      model: '',
      serial: '2A7043B9',
      removable: false,
      protocol: '',
      group: '',
      device: '\\\\.\\PHYSICALDRIVE0',
    },
    {
      name: 'E:',
      identifier: 'E:',
      type: 'disk',
      fsType: 'ntfs',
      mount: 'E:',
      size: '1000202039296',
      physical: 'Local',
      uuid: 'C8EBD118',
      label: 'Data 2',
      model: '',
      serial: 'C8EBD118',
      removable: false,
      protocol: '',
      group: '',
      device: '\\\\.\\PHYSICALDRIVE1',
    },
  ],
  layout: [
    {
      disks: [
        { brand: 'Samsung', device: '\\\\.\\PHYSICALDRIVE2', type: 'NVMe' },
      ],
      size: 500105249280,
    },
    {
      disks: [
        { brand: 'Samsung', device: '\\\\.\\PHYSICALDRIVE0', type: 'SSD' },
      ],
      size: 1000202273280,
    },
    {
      disks: [
        { brand: 'Samsung', device: '\\\\.\\PHYSICALDRIVE1', type: 'NVMe' },
      ],
      size: 1000202273280,
    },
  ],
  output: [178161021440, 880474608128, 606456525312],
} as any as TestCase;

// https://github.com/MauriceNino/dashdot/issues/594
export const TEST_CASE_17 = {
  disks: [
    {
      device: '/dev/sda',
      type: 'HD',
      name: 'MR9240-8i       ',
      vendor: 'LSI',
      size: 291999055872,
      bytesPerSector: null,
      totalCylinders: null,
      totalHeads: null,
      totalSectors: null,
      totalTracks: null,
      tracksPerCylinder: null,
      sectorsPerTrack: null,
      firmwareRevision: '2.13',
      serialNum: '',
      interfaceType: '',
      smartStatus: 'unknown',
      temperature: null,
    },
    {
      device: '/dev/sdb',
      type: 'HD',
      name: 'MR9240-8i       ',
      vendor: 'LSI',
      size: 896998047744,
      bytesPerSector: null,
      totalCylinders: null,
      totalHeads: null,
      totalSectors: null,
      totalTracks: null,
      tracksPerCylinder: null,
      sectorsPerTrack: null,
      firmwareRevision: '2.13',
      serialNum: '',
      interfaceType: '',
      smartStatus: 'unknown',
      temperature: null,
    },
  ],
  sizes: [
    {
      fs: 'overlay',
      type: 'overlay',
      size: 105089261568,
      used: 35669483520,
      available: 64034291712,
      use: 35.78,
      mount: '/',
      rw: false,
    },
    {
      fs: '/dev/mapper/ubuntu--vg-ubuntu--lv',
      type: 'ext4',
      size: 105089261568,
      used: 35669483520,
      available: 64034291712,
      use: 35.78,
      mount: '/mnt/host',
      rw: true,
    },
    {
      fs: '/dev/loop1',
      type: 'squashfs',
      size: 66453504,
      used: 66453504,
      available: 0,
      use: 100,
      mount: '/mnt/host/snap/core20/1778',
      rw: false,
    },
    {
      fs: '/dev/loop2',
      type: 'squashfs',
      size: 108003328,
      used: 108003328,
      available: 0,
      use: 100,
      mount: '/mnt/host/snap/lxd/23541',
      rw: false,
    },
    {
      fs: '/dev/loop4',
      type: 'squashfs',
      size: 52035584,
      used: 52035584,
      available: 0,
      use: 100,
      mount: '/mnt/host/snap/snapd/17883',
      rw: false,
    },
    {
      fs: '/dev/sdb2',
      type: 'fuseblk',
      size: 896979169280,
      used: 107469594624,
      available: 789509574656,
      use: 11.98,
      mount: '/mnt/host/mnt/Pancake-Data',
      rw: true,
    },
    {
      fs: '/dev/sda2',
      type: 'ext4',
      size: 2040373248,
      used: 258015232,
      available: 1658208256,
      use: 13.46,
      mount: '/mnt/host/boot',
      rw: true,
    },
    {
      fs: '//192.168.0.2/SegaMegaDrive',
      type: 'cifs',
      size: 32001783488512,
      used: 21775525765120,
      available: 10226257723392,
      use: 68.04,
      mount: '/mnt/host/mnt/SegaMegaDrive',
      rw: true,
    },
    {
      fs: '192.168.0.6:/mnt/SegaGenesis/SegaGenesisDataset',
      type: 'nfs',
      size: 52162231795712,
      used: 40259038871552,
      available: 11903192924160,
      use: 77.18,
      mount: '/mnt/host/mnt/SegaGenesis',
      rw: false,
    },
    {
      fs: '/dev/loop5',
      type: 'squashfs',
      size: 52297728,
      used: 52297728,
      available: 0,
      use: 100,
      mount: '/mnt/host/snap/snapd/17950',
      rw: false,
    },
    {
      fs: '/dev/loop6',
      type: 'squashfs',
      size: 117440512,
      used: 117440512,
      available: 0,
      use: 100,
      mount: '/mnt/host/snap/lxd/24322',
      rw: false,
    },
    {
      fs: '/dev/loop3',
      type: 'squashfs',
      size: 66453504,
      used: 66453504,
      available: 0,
      use: 100,
      mount: '/mnt/host/snap/core20/1822',
      rw: false,
    },
  ],
  blocks: [
    {
      name: 'sda',
      type: 'disk',
      fsType: '',
      mount: '',
      size: 291999055872,
      physical: 'HDD',
      uuid: '',
      label: '',
      model: 'MR9240-8i',
      serial: '',
      removable: false,
      protocol: '',
      group: '',
      device: '/dev/sda',
    },
    {
      name: 'sdb',
      type: 'disk',
      fsType: '',
      mount: '',
      size: 896998047744,
      physical: 'HDD',
      uuid: '',
      label: '',
      model: 'MR9240-8i',
      serial: '',
      removable: false,
      protocol: '',
      group: '',
      device: '/dev/sdb',
    },
    {
      name: 'loop1',
      type: 'loop',
      fsType: 'squashfs',
      mount: '/mnt/host/snap/core20/1778',
      size: 66347008,
      physical: '',
      uuid: '',
      label: '',
      model: '',
      serial: '',
      removable: false,
      protocol: '',
      group: '',
    },
    {
      name: 'loop2',
      type: 'loop',
      fsType: 'squashfs',
      mount: '/mnt/host/snap/lxd/23541',
      size: 107986944,
      physical: '',
      uuid: '',
      label: '',
      model: '',
      serial: '',
      removable: false,
      protocol: '',
      group: '',
    },
    {
      name: 'loop3',
      type: 'loop',
      fsType: 'squashfs',
      mount: '/mnt/host/snap/core20/1822',
      size: 66355200,
      physical: '',
      uuid: '',
      label: '',
      model: '',
      serial: '',
      removable: false,
      protocol: '',
      group: '',
    },
    {
      name: 'loop4',
      type: 'loop',
      fsType: 'squashfs',
      mount: '/mnt/host/snap/snapd/17883',
      size: 52031488,
      physical: '',
      uuid: '',
      label: '',
      model: '',
      serial: '',
      removable: false,
      protocol: '',
      group: '',
    },
    {
      name: 'loop5',
      type: 'loop',
      fsType: 'squashfs',
      mount: '/mnt/host/snap/snapd/17950',
      size: 52248576,
      physical: '',
      uuid: '',
      label: '',
      model: '',
      serial: '',
      removable: false,
      protocol: '',
      group: '',
    },
    {
      name: 'loop6',
      type: 'loop',
      fsType: 'squashfs',
      mount: '/mnt/host/snap/lxd/24322',
      size: 117387264,
      physical: '',
      uuid: '',
      label: '',
      model: '',
      serial: '',
      removable: false,
      protocol: '',
      group: '',
    },
    {
      name: 'sda1',
      type: 'part',
      fsType: '',
      mount: '',
      size: 1048576,
      physical: '',
      uuid: '',
      label: '',
      model: '',
      serial: '',
      removable: false,
      protocol: '',
      group: '',
      device: '/dev/sda',
    },
    {
      name: 'sda2',
      type: 'part',
      fsType: 'ext4',
      mount: '/mnt/host/boot',
      size: 2147483648,
      physical: '',
      uuid: 'f1639040-f8e2-40db-ba49-40458274a014',
      label: '',
      model: '',
      serial: '',
      removable: false,
      protocol: '',
      group: '',
      device: '/dev/sda',
    },
    {
      name: 'sda3',
      type: 'part',
      fsType: 'LVM2_member',
      mount: '',
      size: 289848426496,
      physical: '',
      uuid: 'mN6Lat-6d5z-R3MI-F4XP-uLFQ-LNAH-5MvmOV',
      label: '',
      model: '',
      serial: '',
      removable: false,
      protocol: '',
      group: '',
      device: '/dev/sda',
    },
    {
      name: 'sdb1',
      type: 'part',
      fsType: '',
      mount: '',
      size: 16759808,
      physical: '',
      uuid: '',
      label: '',
      model: '',
      serial: '',
      removable: false,
      protocol: '',
      group: '',
      device: '/dev/sdb',
    },
    {
      name: 'sdb2',
      type: 'part',
      fsType: 'ntfs',
      mount: '/mnt/host/mnt/Pancake-Data',
      size: 896979173376,
      physical: '',
      uuid: 'E23E57F13E57BCEB',
      label: 'Data',
      model: '',
      serial: '',
      removable: false,
      protocol: '',
      group: '',
      device: '/dev/sdb',
    },
  ],
  layout: [
    {
      disks: [{ brand: 'LSI', device: 'sda', type: 'HD' }],
      size: 291999055872,
    },
    {
      disks: [{ brand: 'LSI', device: 'sdb', type: 'HD' }],
      size: 896998047744,
    },
  ],
  output: [35927498752, 107488473088],
} as any as TestCase;

export const TEST_CASE_18 = {
  disks: [
    {
      device: '/dev/sda',
      type: 'HD',
      name: 'TOSHIBA DT01ACA1',
      vendor: 'Toshiba',
      size: 1000204886016,
      bytesPerSector: null,
      totalCylinders: null,
      totalHeads: null,
      totalSectors: null,
      totalTracks: null,
      tracksPerCylinder: null,
      sectorsPerTrack: null,
      firmwareRevision: 'A7S0',
      serialNum: '',
      interfaceType: 'SATA',
      smartStatus: 'unknown',
      temperature: null,
    },
    {
      device: '/dev/sdb',
      type: 'HD',
      name: 'ST31000528AS    ',
      vendor: 'Seagate',
      size: 1000204886016,
      bytesPerSector: null,
      totalCylinders: null,
      totalHeads: null,
      totalSectors: null,
      totalTracks: null,
      tracksPerCylinder: null,
      sectorsPerTrack: null,
      firmwareRevision: 'CC68',
      serialNum: '',
      interfaceType: 'SATA',
      smartStatus: 'unknown',
      temperature: null,
    },
    {
      device: '/dev/sdc',
      type: 'HD',
      name: 'WDC WD5000AAKX-7',
      vendor: 'Western Digital',
      size: 500107862016,
      bytesPerSector: null,
      totalCylinders: null,
      totalHeads: null,
      totalSectors: null,
      totalTracks: null,
      tracksPerCylinder: null,
      sectorsPerTrack: null,
      firmwareRevision: '1H19',
      serialNum: '',
      interfaceType: 'SATA',
      smartStatus: 'unknown',
      temperature: null,
    },
    {
      device: '/dev/sdd',
      type: 'HD',
      name: 'SAMSUNG HD103UI ',
      vendor: 'Samsung',
      size: 1000204886016,
      bytesPerSector: null,
      totalCylinders: null,
      totalHeads: null,
      totalSectors: null,
      totalTracks: null,
      tracksPerCylinder: null,
      sectorsPerTrack: null,
      firmwareRevision: '1113',
      serialNum: '',
      interfaceType: 'SATA',
      smartStatus: 'unknown',
      temperature: null,
    },
    {
      device: '/dev/sde',
      type: 'HD',
      name: 'DSC2BW240A4     ',
      vendor: 'INTEL SS',
      size: 240057409536,
      bytesPerSector: null,
      totalCylinders: null,
      totalHeads: null,
      totalSectors: null,
      totalTracks: null,
      tracksPerCylinder: null,
      sectorsPerTrack: null,
      firmwareRevision: '0',
      serialNum: '',
      interfaceType: 'USB',
      smartStatus: 'unknown',
      temperature: null,
    },
  ],
  sizes: [
    {
      fs: 'overlay',
      type: 'overlay',
      size: 489518014464,
      used: 91391586304,
      available: 373184999424,
      use: 19.67,
      mount: '/',
      rw: false,
    },
    {
      fs: '/dev/mapper/ubuntu--vg-ubuntu--lv',
      type: 'ext4',
      size: 489518014464,
      used: 91391586304,
      available: 373184999424,
      use: 19.67,
      mount: '/mnt/host',
      rw: true,
    },
    {
      fs: '/dev/loop1',
      type: 'squashfs',
      size: 58327040,
      used: 58327040,
      available: 0,
      use: 100,
      mount: '/mnt/host/snap/core18/2679',
      rw: false,
    },
    {
      fs: '/dev/loop0',
      type: 'squashfs',
      size: 58327040,
      used: 58327040,
      available: 0,
      use: 100,
      mount: '/mnt/host/snap/core18/2697',
      rw: false,
    },
    {
      fs: '/dev/loop3',
      type: 'squashfs',
      size: 66453504,
      used: 66453504,
      available: 0,
      use: 100,
      mount: '/mnt/host/snap/core20/1822',
      rw: false,
    },
    {
      fs: '/dev/loop2',
      type: 'squashfs',
      size: 66453504,
      used: 66453504,
      available: 0,
      use: 100,
      mount: '/mnt/host/snap/core20/1778',
      rw: false,
    },
    {
      fs: '/dev/loop4',
      type: 'squashfs',
      size: 96337920,
      used: 96337920,
      available: 0,
      use: 100,
      mount: '/mnt/host/snap/lxd/23991',
      rw: false,
    },
    {
      fs: '/dev/loop5',
      type: 'squashfs',
      size: 96337920,
      used: 96337920,
      available: 0,
      use: 100,
      mount: '/mnt/host/snap/lxd/24061',
      rw: false,
    },
    {
      fs: '/dev/loop6',
      type: 'squashfs',
      size: 52297728,
      used: 52297728,
      available: 0,
      use: 100,
      mount: '/mnt/host/snap/snapd/17950',
      rw: false,
    },
    {
      fs: '/dev/loop7',
      type: 'squashfs',
      size: 52297728,
      used: 52297728,
      available: 0,
      use: 100,
      mount: '/mnt/host/snap/snapd/18357',
      rw: false,
    },
    {
      fs: '/dev/sde1',
      type: 'ext4',
      size: 202124472320,
      used: 11036561408,
      available: 180746067968,
      use: 5.75,
      mount: '/mnt/host/data',
      rw: true,
    },
    {
      fs: '/dev/md127p1',
      type: 'ext4',
      size: 2951941922816,
      used: 1071917584384,
      available: 1729997443072,
      use: 38.26,
      mount: '/mnt/host/jenkins',
      rw: true,
    },
    {
      fs: '/dev/sdc2',
      type: 'ext4',
      size: 1020702720,
      used: 259330048,
      available: 690909184,
      use: 27.29,
      mount: '/mnt/host/boot',
      rw: true,
    },
    {
      fs: '/dev/sdc1',
      type: 'vfat',
      size: 535805952,
      used: 6344704,
      available: 529461248,
      use: 1.18,
      mount: '/mnt/host/boot/efi',
      rw: true,
    },
  ],
  blocks: [
    {
      name: 'sda',
      type: 'disk',
      fsType: 'linux_raid_member',
      mount: '',
      size: 1000204886016,
      physical: 'HDD',
      uuid: '8dc170a5-b186-2dac-6373-e53261d36e9f',
      label: 'ubuntu-server:jenkins-raid',
      model: 'TOSHIBA DT01ACA1',
      serial: '944UHWZMS',
      removable: false,
      protocol: 'sata',
      group: 'md127',
      device: '/dev/sda',
    },
    {
      name: 'sdb',
      type: 'disk',
      fsType: 'linux_raid_member',
      mount: '',
      size: 1000204886016,
      physical: 'HDD',
      uuid: '8dc170a5-b186-2dac-6373-e53261d36e9f',
      label: 'ubuntu-server:jenkins-raid',
      model: 'ST31000528AS',
      serial: '6VPBTKP0',
      removable: false,
      protocol: 'sata',
      group: 'md127',
      device: '/dev/sdb',
    },
    {
      name: 'sdc',
      type: 'disk',
      fsType: '',
      mount: '',
      size: 500107862016,
      physical: 'HDD',
      uuid: '',
      label: '',
      model: 'WDC WD5000AAKX-7',
      serial: 'WD-WCC2ESM09747',
      removable: false,
      protocol: 'sata',
      group: '',
      device: '/dev/sdc',
    },
    {
      name: 'sdd',
      type: 'disk',
      fsType: 'linux_raid_member',
      mount: '',
      size: 1000204886016,
      physical: 'HDD',
      uuid: '8dc170a5-b186-2dac-6373-e53261d36e9f',
      label: 'ubuntu-server:jenkins-raid',
      model: 'SAMSUNG HD103UI',
      serial: 'S1LMJ1NQB08090',
      removable: false,
      protocol: 'sata',
      group: 'md127',
      device: '/dev/sdd',
    },
    {
      name: 'sde',
      type: 'disk',
      fsType: '',
      mount: '',
      size: 240057409536,
      physical: 'HDD',
      uuid: '',
      label: '',
      model: 'DSC2BW240A4',
      serial: '210987654321',
      removable: false,
      protocol: 'usb',
      group: '',
      device: '/dev/sde',
    },
    {
      name: 'zram0',
      type: 'disk',
      fsType: '',
      mount: '[SWAP]',
      size: 8341528576,
      physical: 'SSD',
      uuid: '',
      label: '',
      model: '',
      serial: '',
      removable: false,
      protocol: '',
      group: '',
      device: '/dev/zram0',
    },
    {
      name: 'loop0',
      type: 'loop',
      fsType: 'squashfs',
      mount: '/snap/core18/2697',
      size: 58310656,
      physical: '',
      uuid: '',
      label: '',
      model: '',
      serial: '',
      removable: false,
      protocol: '',
      group: '',
    },
    {
      name: 'loop1',
      type: 'loop',
      fsType: 'squashfs',
      mount: '/snap/core18/2679',
      size: 58310656,
      physical: '',
      uuid: '',
      label: '',
      model: '',
      serial: '',
      removable: false,
      protocol: '',
      group: '',
    },
    {
      name: 'loop2',
      type: 'loop',
      fsType: 'squashfs',
      mount: '/snap/core20/1778',
      size: 66347008,
      physical: '',
      uuid: '',
      label: '',
      model: '',
      serial: '',
      removable: false,
      protocol: '',
      group: '',
    },
    {
      name: 'loop3',
      type: 'loop',
      fsType: 'squashfs',
      mount: '/snap/core20/1822',
      size: 66355200,
      physical: '',
      uuid: '',
      label: '',
      model: '',
      serial: '',
      removable: false,
      protocol: '',
      group: '',
    },
    {
      name: 'loop4',
      type: 'loop',
      fsType: 'squashfs',
      mount: '/snap/lxd/23991',
      size: 96272384,
      physical: '',
      uuid: '',
      label: '',
      model: '',
      serial: '',
      removable: false,
      protocol: '',
      group: '',
    },
    {
      name: 'loop5',
      type: 'loop',
      fsType: 'squashfs',
      mount: '/snap/lxd/24061',
      size: 96292864,
      physical: '',
      uuid: '',
      label: '',
      model: '',
      serial: '',
      removable: false,
      protocol: '',
      group: '',
    },
    {
      name: 'loop6',
      type: 'loop',
      fsType: 'squashfs',
      mount: '/snap/snapd/17950',
      size: 52248576,
      physical: '',
      uuid: '',
      label: '',
      model: '',
      serial: '',
      removable: false,
      protocol: '',
      group: '',
    },
    {
      name: 'loop7',
      type: 'loop',
      fsType: 'squashfs',
      mount: '/snap/snapd/18357',
      size: 52260864,
      physical: '',
      uuid: '',
      label: '',
      model: '',
      serial: '',
      removable: false,
      protocol: '',
      group: '',
    },
    {
      name: 'ubuntu--vg-ubuntu--lv',
      type: 'lvm',
      fsType: 'ext4',
      mount: '/mnt/host',
      size: 498493030400,
      physical: '',
      uuid: '01250a10-38b9-4fab-9b73-70c392128944',
      label: '',
      model: '',
      serial: '',
      removable: false,
      protocol: '',
      group: '',
    },
    {
      name: 'md127p1',
      type: 'part',
      fsType: 'ext4',
      mount: '/mnt/host/jenkins',
      size: 3000202428416,
      physical: '',
      uuid: '5825e044-f036-492f-9f16-a82a80ece7a0',
      label: '',
      model: '',
      serial: '',
      removable: false,
      protocol: '',
      group: '',
    },
    {
      name: 'sdc1',
      type: 'part',
      fsType: 'vfat',
      mount: '/mnt/host/boot/efi',
      size: 536870912,
      physical: '',
      uuid: '2F60-D8B9',
      label: '',
      model: '',
      serial: '',
      removable: false,
      protocol: '',
      group: '',
      device: '/dev/sdc',
    },
    {
      name: 'sdc2',
      type: 'part',
      fsType: 'ext4',
      mount: '/mnt/host/boot',
      size: 1073741824,
      physical: '',
      uuid: '19c0ed21-5421-41df-bb5a-c52cb9b1b0bd',
      label: '',
      model: '',
      serial: '',
      removable: false,
      protocol: '',
      group: '',
      device: '/dev/sdc',
    },
    {
      name: 'sdc3',
      type: 'part',
      fsType: 'LVM2_member',
      mount: '',
      size: 498495127552,
      physical: '',
      uuid: '4yBE54-pniv-sVZ0-1Xu2-g3np-GOVj-9dpDWx',
      label: '',
      model: '',
      serial: '',
      removable: false,
      protocol: '',
      group: '',
      device: '/dev/sdc',
    },
    {
      name: 'sde1',
      type: 'part',
      fsType: 'ext4',
      mount: '/mnt/host/data',
      size: 206501314560,
      physical: '',
      uuid: '97c35fac-c0f1-4e3c-8c38-eedea9072dc2',
      label: 'rpi-data',
      model: '',
      serial: '',
      removable: false,
      protocol: '',
      group: '',
      device: '/dev/sde',
    },
    {
      name: 'sde2',
      type: 'part',
      fsType: 'swap',
      mount: '',
      size: 33554432000,
      physical: '',
      uuid: '270963e1-6445-49f8-93bf-96669a8916c4',
      label: '',
      model: '',
      serial: '',
      removable: false,
      protocol: '',
      group: '',
      device: '/dev/sde',
    },
    {
      name: 'md127',
      type: 'raid0',
      fsType: '',
      mount: '',
      size: 3000208195584,
      physical: '',
      uuid: '8dc170a5-b186-2dac-6373-e53261d36e9f',
      label: 'ubuntu-server:jenkins-raid',
      model: '',
      serial: '',
      removable: false,
      protocol: '',
      group: '',
    },
  ],
  layout: [
    {
      disks: [
        { brand: 'Toshiba', device: 'sda', type: 'HD' },
        { brand: 'Seagate', device: 'sdb', type: 'HD' },
        { brand: 'Samsung', device: 'sdd', type: 'HD' },
      ],
      raidLabel: 'ubuntu-server',
      raidName: 'md127',
      raidType: 0,
      size: 3000208195584,
    },
    {
      disks: [{ brand: 'Western Digital', device: 'sdc', type: 'HD' }],
      size: 500107862016,
    },
    {
      disks: [{ brand: 'INTEL SS', device: 'sde', type: 'HD' }],
      size: 240057409536,
    },
  ],
  output: [1120183857152, 91657261056, 48969498624],
} as any as TestCase;

export const TEST_CASE_19 = {
  disks: [
    {
      device: '/dev/sda',
      type: 'HD',
      name: 'DataTraveler 2.0',
      vendor: 'Kingston',
      size: 15502147584,
      bytesPerSector: null,
      totalCylinders: null,
      totalHeads: null,
      totalSectors: null,
      totalTracks: null,
      tracksPerCylinder: null,
      sectorsPerTrack: null,
      firmwareRevision: 'PMAP',
      serialNum: '',
      interfaceType: 'USB',
      smartStatus: 'unknown',
      temperature: null,
    },
    {
      device: '/dev/sdb',
      type: 'SSD',
      name: 'KINGSTON SA400S3',
      vendor: 'Kingston Technology',
      size: 480103981056,
      bytesPerSector: null,
      totalCylinders: null,
      totalHeads: null,
      totalSectors: null,
      totalTracks: null,
      tracksPerCylinder: null,
      sectorsPerTrack: null,
      firmwareRevision: 'K1C3',
      serialNum: '',
      interfaceType: 'SATA',
      smartStatus: 'unknown',
      temperature: null,
    },
    {
      device: '/dev/sdc',
      type: 'SSD',
      name: 'Samsung SSD 870 ',
      vendor: 'Samsung',
      size: 1000204886016,
      bytesPerSector: null,
      totalCylinders: null,
      totalHeads: null,
      totalSectors: null,
      totalTracks: null,
      tracksPerCylinder: null,
      sectorsPerTrack: null,
      firmwareRevision: '2B6Q',
      serialNum: '',
      interfaceType: 'SATA',
      smartStatus: 'unknown',
      temperature: null,
    },
    {
      device: '/dev/sdd',
      type: 'SSD',
      name: 'KINGSTON SA400S3',
      vendor: 'Kingston Technology',
      size: 960197124096,
      bytesPerSector: null,
      totalCylinders: null,
      totalHeads: null,
      totalSectors: null,
      totalTracks: null,
      tracksPerCylinder: null,
      sectorsPerTrack: null,
      firmwareRevision: 'K1C3',
      serialNum: '',
      interfaceType: 'SATA',
      smartStatus: 'unknown',
      temperature: null,
    },
    {
      device: '/dev/sde',
      type: 'HD',
      name: 'TOSHIBA MG07ACA1',
      vendor: 'Toshiba',
      size: 14000519643136,
      bytesPerSector: null,
      totalCylinders: null,
      totalHeads: null,
      totalSectors: null,
      totalTracks: null,
      tracksPerCylinder: null,
      sectorsPerTrack: null,
      firmwareRevision: '0103',
      serialNum: '',
      interfaceType: 'SAS',
      smartStatus: 'unknown',
      temperature: null,
    },
    {
      device: '/dev/sdf',
      type: 'HD',
      name: 'ST8000VN004-2M21',
      vendor: 'Seagate',
      size: 8001563222016,
      bytesPerSector: null,
      totalCylinders: null,
      totalHeads: null,
      totalSectors: null,
      totalTracks: null,
      tracksPerCylinder: null,
      sectorsPerTrack: null,
      firmwareRevision: 'SC60',
      serialNum: '',
      interfaceType: 'SAS',
      smartStatus: 'unknown',
      temperature: null,
    },
    {
      device: '/dev/sdg',
      type: 'HD',
      name: 'ST8000VN004-2M21',
      vendor: 'Seagate',
      size: 8001563222016,
      bytesPerSector: null,
      totalCylinders: null,
      totalHeads: null,
      totalSectors: null,
      totalTracks: null,
      tracksPerCylinder: null,
      sectorsPerTrack: null,
      firmwareRevision: 'SC60',
      serialNum: '',
      interfaceType: 'SAS',
      smartStatus: 'unknown',
      temperature: null,
    },
    {
      device: '/dev/sdh',
      type: 'HD',
      name: 'ST4000VN008-2DR1',
      vendor: 'Seagate',
      size: 4000787030016,
      bytesPerSector: null,
      totalCylinders: null,
      totalHeads: null,
      totalSectors: null,
      totalTracks: null,
      tracksPerCylinder: null,
      sectorsPerTrack: null,
      firmwareRevision: 'SC60',
      serialNum: '',
      interfaceType: 'SAS',
      smartStatus: 'unknown',
      temperature: null,
    },
    {
      device: '/dev/sdi',
      type: 'HD',
      name: 'ST4000VN008-2DR1',
      vendor: 'Seagate',
      size: 4000787030016,
      bytesPerSector: null,
      totalCylinders: null,
      totalHeads: null,
      totalSectors: null,
      totalTracks: null,
      tracksPerCylinder: null,
      sectorsPerTrack: null,
      firmwareRevision: 'SC60',
      serialNum: '',
      interfaceType: 'SAS',
      smartStatus: 'unknown',
      temperature: null,
    },
    {
      device: '/dev/sdj',
      type: 'HD',
      name: 'ST4000VN008-2DR1',
      vendor: 'Seagate',
      size: 4000787030016,
      bytesPerSector: null,
      totalCylinders: null,
      totalHeads: null,
      totalSectors: null,
      totalTracks: null,
      tracksPerCylinder: null,
      sectorsPerTrack: null,
      firmwareRevision: 'SC60',
      serialNum: '',
      interfaceType: 'SAS',
      smartStatus: 'unknown',
      temperature: null,
    },
    {
      device: '/dev/sdk',
      type: 'HD',
      name: 'ST4000VN008-2DR1',
      vendor: 'Seagate',
      size: 4000787030016,
      bytesPerSector: null,
      totalCylinders: null,
      totalHeads: null,
      totalSectors: null,
      totalTracks: null,
      tracksPerCylinder: null,
      sectorsPerTrack: null,
      firmwareRevision: 'SC60',
      serialNum: '',
      interfaceType: 'SAS',
      smartStatus: 'unknown',
      temperature: null,
    },
  ],
  sizes: [
    {
      fs: '/dev/loop2',
      type: 'btrfs',
      size: 53687091200,
      used: 20404056064,
      available: 31226925056,
      use: 39.52,
      mount: '/',
      rw: true,
    },
    {
      fs: '/dev/sda1',
      type: 'vfat',
      size: 15485943808,
      used: 680329216,
      available: 14805614592,
      use: 4.39,
      mount: '/mnt/host/boot',
      rw: true,
    },
    {
      fs: '/dev/loop0',
      type: 'squashfs',
      size: 16724692992,
      used: 875978752,
      available: 15848714240,
      use: 5.24,
      mount: '/mnt/host/lib/firmware',
      rw: false,
    },
    {
      fs: 'overlay',
      type: 'overlay',
      size: 16724692992,
      used: 875978752,
      available: 15848714240,
      use: 5.24,
      mount: '/mnt/host/lib/firmware',
      rw: false,
    },
    {
      fs: '/dev/loop1',
      type: 'squashfs',
      size: 16724692992,
      used: 875978752,
      available: 15848714240,
      use: 5.24,
      mount: '/mnt/host/lib/modules',
      rw: false,
    },
    {
      fs: '/dev/md1',
      type: 'xfs',
      size: 3998833471488,
      used: 2526756556800,
      available: 1472076914688,
      use: 63.19,
      mount: '/mnt/host/mnt/disk1',
      rw: true,
    },
    {
      fs: '/dev/md2',
      type: 'xfs',
      size: 3998833471488,
      used: 3930067537920,
      available: 68765933568,
      use: 98.28,
      mount: '/mnt/host/mnt/disk2',
      rw: true,
    },
    {
      fs: '/dev/md3',
      type: 'xfs',
      size: 3998833471488,
      used: 3755402776576,
      available: 243430694912,
      use: 93.91,
      mount: '/mnt/host/mnt/disk3',
      rw: true,
    },
    {
      fs: '/dev/md4',
      type: 'xfs',
      size: 3998833471488,
      used: 3789034754048,
      available: 209798717440,
      use: 94.75,
      mount: '/mnt/host/mnt/disk4',
      rw: true,
    },
    {
      fs: '/dev/md5',
      type: 'xfs',
      size: 7999426170880,
      used: 7385656987648,
      available: 613769183232,
      use: 92.33,
      mount: '/mnt/host/mnt/disk5',
      rw: true,
    },
    {
      fs: '/dev/sdc1',
      type: 'xfs',
      size: 999715459072,
      used: 462745698304,
      available: 536969760768,
      use: 46.29,
      mount: '/mnt/host/mnt/cache',
      rw: true,
    },
    {
      fs: '/dev/sdb1',
      type: 'xfs',
      size: 479868510208,
      used: 129046470656,
      available: 350822039552,
      use: 26.89,
      mount: '/mnt/host/mnt/cache_vm',
      rw: true,
    },
    {
      fs: '/dev/sde1',
      type: 'xfs',
      size: 13998382592000,
      used: 11663760277504,
      available: 2334622314496,
      use: 83.32,
      mount: '/mnt/host/mnt/downloads',
      rw: true,
    },
    {
      fs: '/dev/sdd1',
      type: 'xfs',
      size: 959727230976,
      used: 6725234688,
      available: 953001996288,
      use: 0.7,
      mount: '/mnt/host/mnt/downloads_temp',
      rw: true,
    },
    {
      fs: 'shfs',
      type: 'fuse.shfs',
      size: 23994760056832,
      used: 21386918612992,
      available: 2607841443840,
      use: 89.13,
      mount: '/mnt/host/mnt/user0',
      rw: false,
    },
    {
      fs: '/dev/loop3',
      type: 'btrfs',
      size: 1073741824,
      used: 4386816,
      available: 948015104,
      use: 0.46,
      mount: '/mnt/host/etc/libvirt',
      rw: true,
    },
  ],
  blocks: [
    {
      name: 'sda',
      type: 'disk',
      fsType: '',
      mount: '',
      size: 15502147584,
      physical: 'HDD',
      uuid: '',
      label: '',
      model: 'DataTraveler 2.0',
      serial: '',
      removable: true,
      protocol: 'usb',
      group: '',
      device: '/dev/sda',
    },
    {
      name: 'sdb',
      type: 'disk',
      fsType: '',
      mount: '',
      size: 480103981056,
      physical: 'SSD',
      uuid: '',
      label: '',
      model: 'KINGSTON SA400S3',
      serial: '',
      removable: false,
      protocol: 'sata',
      group: '',
      device: '/dev/sdb',
    },
    {
      name: 'sdc',
      type: 'disk',
      fsType: '',
      mount: '',
      size: 1000204886016,
      physical: 'SSD',
      uuid: '',
      label: '',
      model: 'Samsung SSD 870',
      serial: '',
      removable: false,
      protocol: 'sata',
      group: '',
      device: '/dev/sdc',
    },
    {
      name: 'sdd',
      type: 'disk',
      fsType: '',
      mount: '',
      size: 960197124096,
      physical: 'SSD',
      uuid: '',
      label: '',
      model: 'KINGSTON SA400S3',
      serial: '',
      removable: false,
      protocol: 'sata',
      group: '',
      device: '/dev/sdd',
    },
    {
      name: 'sde',
      type: 'disk',
      fsType: '',
      mount: '',
      size: 14000519643136,
      physical: 'HDD',
      uuid: '',
      label: '',
      model: 'TOSHIBA MG07ACA1',
      serial: '',
      removable: false,
      protocol: 'sas',
      group: '',
      device: '/dev/sde',
    },
    {
      name: 'sdf',
      type: 'disk',
      fsType: '',
      mount: '',
      size: 8001563222016,
      physical: 'HDD',
      uuid: '',
      label: '',
      model: 'ST8000VN004-2M21',
      serial: '',
      removable: false,
      protocol: 'sas',
      group: '',
      device: '/dev/sdf',
    },
    {
      name: 'sdg',
      type: 'disk',
      fsType: '',
      mount: '',
      size: 8001563222016,
      physical: 'HDD',
      uuid: '',
      label: '',
      model: 'ST8000VN004-2M21',
      serial: '',
      removable: false,
      protocol: 'sas',
      group: '',
      device: '/dev/sdg',
    },
    {
      name: 'sdh',
      type: 'disk',
      fsType: '',
      mount: '',
      size: 4000787030016,
      physical: 'HDD',
      uuid: '',
      label: '',
      model: 'ST4000VN008-2DR1',
      serial: '',
      removable: false,
      protocol: 'sas',
      group: '',
      device: '/dev/sdh',
    },
    {
      name: 'sdi',
      type: 'disk',
      fsType: '',
      mount: '',
      size: 4000787030016,
      physical: 'HDD',
      uuid: '',
      label: '',
      model: 'ST4000VN008-2DR1',
      serial: '',
      removable: false,
      protocol: 'sas',
      group: '',
      device: '/dev/sdi',
    },
    {
      name: 'sdj',
      type: 'disk',
      fsType: '',
      mount: '',
      size: 4000787030016,
      physical: 'HDD',
      uuid: '',
      label: '',
      model: 'ST4000VN008-2DR1',
      serial: '',
      removable: false,
      protocol: 'sas',
      group: '',
      device: '/dev/sdj',
    },
    {
      name: 'sdk',
      type: 'disk',
      fsType: '',
      mount: '',
      size: 4000787030016,
      physical: 'HDD',
      uuid: '',
      label: '',
      model: 'ST4000VN008-2DR1',
      serial: '',
      removable: false,
      protocol: 'sas',
      group: '',
      device: '/dev/sdk',
    },
    {
      name: 'loop0',
      type: 'loop',
      fsType: 'squashfs',
      mount: '/mnt/host/lib/firmware',
      size: 115998720,
      physical: '',
      uuid: '',
      label: '',
      model: '',
      serial: '',
      removable: false,
      protocol: '',
      group: '',
    },
    {
      name: 'loop1',
      type: 'loop',
      fsType: 'squashfs',
      mount: '/mnt/host/lib/modules',
      size: 18239488,
      physical: '',
      uuid: '',
      label: '',
      model: '',
      serial: '',
      removable: false,
      protocol: '',
      group: '',
    },
    {
      name: 'loop2',
      type: 'loop',
      fsType: 'btrfs',
      mount: '/mnt/host/var/lib/docker',
      size: 53687091200,
      physical: '',
      uuid: '5498eb9d-3188-46b5-b78c-8b897e191157',
      label: '',
      model: '',
      serial: '',
      removable: false,
      protocol: '',
      group: '',
    },
    {
      name: 'loop3',
      type: 'loop',
      fsType: 'btrfs',
      mount: '/mnt/host/etc/libvirt',
      size: 1073741824,
      physical: '',
      uuid: '20e60d9d-3bf5-4bc6-864f-87bfecd106fb',
      label: '',
      model: '',
      serial: '',
      removable: false,
      protocol: '',
      group: '',
    },
    {
      name: 'md1',
      type: 'md',
      fsType: 'xfs',
      mount: '/mnt/host/mnt/disk1',
      size: 4000786976768,
      physical: '',
      uuid: '968f9568-e420-4ede-b44f-6f262cc3c377',
      label: '',
      model: '',
      serial: '',
      removable: false,
      protocol: '',
      group: '',
    },
    {
      name: 'md2',
      type: 'md',
      fsType: 'xfs',
      mount: '/mnt/host/mnt/disk2',
      size: 4000786976768,
      physical: '',
      uuid: '6d91cadf-d222-4b8a-aabc-8ddae3996c86',
      label: '',
      model: '',
      serial: '',
      removable: false,
      protocol: '',
      group: '',
    },
    {
      name: 'md3',
      type: 'md',
      fsType: 'xfs',
      mount: '/mnt/host/mnt/disk3',
      size: 4000786976768,
      physical: '',
      uuid: '7efdedb8-a050-4db1-bace-49ae3461cce8',
      label: '',
      model: '',
      serial: '',
      removable: false,
      protocol: '',
      group: '',
    },
    {
      name: 'md4',
      type: 'md',
      fsType: 'xfs',
      mount: '/mnt/host/mnt/disk4',
      size: 4000786976768,
      physical: '',
      uuid: '6fdb788a-dcb5-40ad-9873-feba207d6d1f',
      label: '',
      model: '',
      serial: '',
      removable: false,
      protocol: '',
      group: '',
    },
    {
      name: 'md5',
      type: 'md',
      fsType: 'xfs',
      mount: '/mnt/host/mnt/disk5',
      size: 8001563168768,
      physical: '',
      uuid: 'a554c96b-d5d3-4ff7-9d0f-1ed806e820e4',
      label: '',
      model: '',
      serial: '',
      removable: false,
      protocol: '',
      group: '',
    },
    {
      name: 'sda1',
      type: 'part',
      fsType: 'vfat',
      mount: '/mnt/host/boot',
      size: 15501099008,
      physical: '',
      uuid: '272C-EBE2',
      label: 'UNRAID',
      model: '',
      serial: '',
      removable: true,
      protocol: '',
      group: '',
      device: '/dev/sda',
    },
    {
      name: 'sdb1',
      type: 'part',
      fsType: 'xfs',
      mount: '/mnt/host/mnt/cache_vm',
      size: 480102932480,
      physical: '',
      uuid: 'b9bf4c50-a608-4ba5-9ad3-c8cfbba8db48',
      label: '',
      model: '',
      serial: '',
      removable: false,
      protocol: '',
      group: '',
      device: '/dev/sdb',
    },
    {
      name: 'sdc1',
      type: 'part',
      fsType: 'xfs',
      mount: '/mnt/host/mnt/cache',
      size: 1000203837440,
      physical: '',
      uuid: 'd2c21e37-795e-4f98-99f7-bd942e2ce3ed',
      label: '',
      model: '',
      serial: '',
      removable: false,
      protocol: '',
      group: '',
      device: '/dev/sdc',
    },
    {
      name: 'sdd1',
      type: 'part',
      fsType: 'xfs',
      mount: '/mnt/host/mnt/downloads_temp',
      size: 960196075520,
      physical: '',
      uuid: '49b45b84-2f5c-436e-945d-62cd1cdc4359',
      label: '',
      model: '',
      serial: '',
      removable: false,
      protocol: '',
      group: '',
      device: '/dev/sdd',
    },
    {
      name: 'sde1',
      type: 'part',
      fsType: 'xfs',
      mount: '/mnt/host/mnt/downloads',
      size: 14000519593472,
      physical: '',
      uuid: '1c1bad35-7695-4c99-b9b4-1bbbf3124ed6',
      label: '',
      model: '',
      serial: '',
      removable: false,
      protocol: '',
      group: '',
      device: '/dev/sde',
    },
    {
      name: 'sdf1',
      type: 'part',
      fsType: '',
      mount: '',
      size: 8001563172352,
      physical: '',
      uuid: '',
      label: '',
      model: '',
      serial: '',
      removable: false,
      protocol: '',
      group: '',
      device: '/dev/sdf',
    },
    {
      name: 'sdg1',
      type: 'part',
      fsType: 'xfs',
      mount: '',
      size: 8001563172352,
      physical: '',
      uuid: 'a554c96b-d5d3-4ff7-9d0f-1ed806e820e4',
      label: '',
      model: '',
      serial: '',
      removable: false,
      protocol: '',
      group: '',
      device: '/dev/sdg',
    },
    {
      name: 'sdh1',
      type: 'part',
      fsType: 'xfs',
      mount: '',
      size: 4000786980352,
      physical: '',
      uuid: '6d91cadf-d222-4b8a-aabc-8ddae3996c86',
      label: '',
      model: '',
      serial: '',
      removable: false,
      protocol: '',
      group: '',
      device: '/dev/sdh',
    },
    {
      name: 'sdi1',
      type: 'part',
      fsType: 'xfs',
      mount: '',
      size: 4000786980352,
      physical: '',
      uuid: '968f9568-e420-4ede-b44f-6f262cc3c377',
      label: '',
      model: '',
      serial: '',
      removable: false,
      protocol: '',
      group: '',
      device: '/dev/sdi',
    },
    {
      name: 'sdj1',
      type: 'part',
      fsType: 'xfs',
      mount: '',
      size: 4000786980352,
      physical: '',
      uuid: '7efdedb8-a050-4db1-bace-49ae3461cce8',
      label: '',
      model: '',
      serial: '',
      removable: false,
      protocol: '',
      group: '',
      device: '/dev/sdj',
    },
    {
      name: 'sdk1',
      type: 'part',
      fsType: 'xfs',
      mount: '',
      size: 4000786980352,
      physical: '',
      uuid: '6fdb788a-dcb5-40ad-9873-feba207d6d1f',
      label: '',
      model: '',
      serial: '',
      removable: false,
      protocol: '',
      group: '',
      device: '/dev/sdk',
    },
  ],
  layout: [
    {
      size: 480103981056,
      disks: [{ device: 'sdb', brand: 'Kingston Technology', type: 'SSD' }],
    },
    {
      size: 1000204886016,
      disks: [{ device: 'sdc', brand: 'Samsung', type: 'SSD' }],
    },
    {
      size: 480103981056,
      disks: [{ device: 'sdd', brand: 'Kingston Technology', type: 'SSD' }],
    },
    {
      size: 14000519643136,
      disks: [{ device: 'sde', brand: 'Toshiba', type: 'HD' }],
    },
    {
      size: 8001563222016,
      disks: [{ device: 'sdf', brand: 'Seagate', type: 'HD' }],
    },
    {
      size: 8001563222016,
      disks: [{ device: 'sdg', brand: 'Seagate', type: 'HD' }],
    },
    {
      size: 4000787030016,
      disks: [{ device: 'sdh', brand: 'Seagate', type: 'HD' }],
    },
    {
      size: 4000787030016,
      disks: [{ device: 'sdi', brand: 'Seagate', type: 'HD' }],
    },
    {
      size: 4000787030016,
      disks: [{ device: 'sdj', brand: 'Seagate', type: 'HD' }],
    },
    {
      size: 4000787030016,
      disks: [{ device: 'sdk', brand: 'Seagate', type: 'HD' }],
    },
  ],
  output: [
    129281941504, 463235125248, 6725234688, 11665897328640, -1, 7387794038784,
    3932021096448, 2528710115328, 3757356335104, 3790988312576,
  ],
} as any as TestCase;

export const TEST_CASE_20 = {
  disks: [
    {
      device: '/dev/sda',
      type: 'SSD',
      name: 'OCZ-VERTEX3     ',
      vendor: 'ATA',
      size: 120034123776,
      bytesPerSector: null,
      totalCylinders: null,
      totalHeads: null,
      totalSectors: null,
      totalTracks: null,
      tracksPerCylinder: null,
      sectorsPerTrack: null,
      firmwareRevision: '2.25',
      serialNum: '',
      interfaceType: 'SATA',
      smartStatus: 'unknown',
      temperature: null,
    },
    {
      device: '/dev/sdb',
      type: 'HD',
      name: 'WDC WD40EFRX-68W',
      vendor: 'Western Digital',
      size: 4000787030016,
      bytesPerSector: null,
      totalCylinders: null,
      totalHeads: null,
      totalSectors: null,
      totalTracks: null,
      tracksPerCylinder: null,
      sectorsPerTrack: null,
      firmwareRevision: '0A82',
      serialNum: '',
      interfaceType: 'USB',
      smartStatus: 'unknown',
      temperature: null,
    },
    {
      device: '/dev/nvme0n1',
      type: 'NVMe',
      name: 'HJDK SSD 512GB                          ',
      vendor: '',
      size: 512110190592,
      bytesPerSector: null,
      totalCylinders: null,
      totalHeads: null,
      totalSectors: null,
      totalTracks: null,
      tracksPerCylinder: null,
      sectorsPerTrack: null,
      firmwareRevision: '',
      serialNum: 'AA000000000000000003',
      interfaceType: 'PCIe',
      smartStatus: 'unknown',
      temperature: null,
    },
  ],
  sizes: [
    {
      fs: 'overlay',
      type: 'overlay',
      size: 116012584960,
      used: 16712163328,
      available: 93360029696,
      use: 15.18,
      mount: '/',
      rw: false,
    },
    {
      fs: '/dev/sda2',
      type: 'ext4',
      size: 116012584960,
      used: 16712163328,
      available: 93360029696,
      use: 15.18,
      mount: '/mnt/host',
      rw: true,
    },
    {
      fs: '/dev/sda1',
      type: 'vfat',
      size: 535801856,
      used: 155648,
      available: 535646208,
      use: 0.03,
      mount: '/mnt/host/boot/efi',
      rw: true,
    },
    {
      fs: '/dev/sdb2',
      type: 'ext4',
      size: 3936483074048,
      used: 1413829738496,
      available: 2322614407168,
      use: 37.84,
      mount:
        '/mnt/host/srv/dev-disk-by-uuid-c9e750f7-7ebe-4706-abd9-ce7788429acd',
      rw: true,
    },
  ],
  blocks: [
    {
      name: 'nvme0n1',
      type: 'disk',
      fsType: '',
      mount: '',
      size: 512110190592,
      physical: 'SSD',
      uuid: '',
      label: '',
      model: 'HJDK SSD 512GB',
      serial: 'AA000000000000000003',
      removable: false,
      protocol: 'nvme',
      group: '',
      device: '/dev/nvme0n1',
    },
    {
      name: 'sda',
      type: 'disk',
      fsType: '',
      mount: '',
      size: 120034123776,
      physical: 'SSD',
      uuid: '',
      label: '',
      model: 'OCZ-VERTEX3',
      serial: '',
      removable: false,
      protocol: 'sata',
      group: '',
      device: '/dev/sda',
    },
    {
      name: 'sdb',
      type: 'disk',
      fsType: '',
      mount: '',
      size: 4000787030016,
      physical: 'HDD',
      uuid: '',
      label: '',
      model: 'WDC WD40EFRX-68W',
      serial: '',
      removable: false,
      protocol: 'usb',
      group: '',
      device: '/dev/sdb',
    },
    {
      name: 'nvme0n1p1',
      type: 'part',
      fsType: 'vfat',
      mount: '',
      size: 104857600,
      physical: '',
      uuid: '4878-28DA',
      label: 'SYSTEM',
      model: '',
      serial: '',
      removable: false,
      protocol: 'nvme',
      group: '',
      device: '/dev/nvme0n1',
    },
    {
      name: 'nvme0n1p2',
      type: 'part',
      fsType: '',
      mount: '',
      size: 16777216,
      physical: '',
      uuid: '',
      label: '',
      model: '',
      serial: '',
      removable: false,
      protocol: 'nvme',
      group: '',
      device: '/dev/nvme0n1',
    },
    {
      name: 'nvme0n1p3',
      type: 'part',
      fsType: 'ntfs',
      mount: '',
      size: 510131175424,
      physical: '',
      uuid: '4CCA7942CA79297A',
      label: '',
      model: '',
      serial: '',
      removable: false,
      protocol: 'nvme',
      group: '',
      device: '/dev/nvme0n1',
    },
    {
      name: 'nvme0n1p4',
      type: 'part',
      fsType: 'ntfs',
      mount: '',
      size: 1855979520,
      physical: '',
      uuid: 'C8487B45487B3174',
      label: 'Recovery',
      model: '',
      serial: '',
      removable: false,
      protocol: 'nvme',
      group: '',
      device: '/dev/nvme0n1',
    },
    {
      name: 'sda1',
      type: 'part',
      fsType: 'vfat',
      mount: '/mnt/host/boot/efi',
      size: 536870912,
      physical: '',
      uuid: '75D6-EBBF',
      label: '',
      model: '',
      serial: '',
      removable: false,
      protocol: '',
      group: '',
      device: '/dev/sda',
    },
    {
      name: 'sda2',
      type: 'part',
      fsType: 'ext4',
      mount: '/mnt/host',
      size: 118472310784,
      physical: '',
      uuid: 'b30cbbd7-bec4-4437-9d6f-a149365842dc',
      label: '',
      model: '',
      serial: '',
      removable: false,
      protocol: '',
      group: '',
      device: '/dev/sda',
    },
    {
      name: 'sda3',
      type: 'part',
      fsType: 'swap',
      mount: '[SWAP]',
      size: 1023410176,
      physical: '',
      uuid: '5a8b9c3b-618b-4c18-b201-a0e56473a781',
      label: '',
      model: '',
      serial: '',
      removable: false,
      protocol: '',
      group: '',
      device: '/dev/sda',
    },
    {
      name: 'sdb1',
      type: 'part',
      fsType: 'vfat',
      mount: '',
      size: 209715200,
      physical: '',
      uuid: '67E3-17ED',
      label: 'EFI',
      model: '',
      serial: '',
      removable: false,
      protocol: '',
      group: '',
      device: '/dev/sdb',
    },
    {
      name: 'sdb2',
      type: 'part',
      fsType: 'ext4',
      mount: '/mnt/host/sftp/mataleao/Garbage',
      size: 4000443056128,
      physical: '',
      uuid: 'c9e750f7-7ebe-4706-abd9-ce7788429acd',
      label: 'Garbage',
      model: '',
      serial: '',
      removable: false,
      protocol: '',
      group: '',
      device: '/dev/sdb',
    },
    {
      name: 'sdb3',
      type: 'part',
      fsType: 'hfsplus',
      mount: '',
      size: 134217728,
      physical: '',
      uuid: '1ee90a98-51e2-3ce5-9486-40efe12c7952',
      label: 'Boot OS X',
      model: '',
      serial: '',
      removable: false,
      protocol: '',
      group: '',
      device: '/dev/sdb',
    },
  ],
  layout: [
    {
      disks: [{ brand: '', device: 'nvme0n1', type: 'NVMe' }],
      size: 512110190592,
    },
    {
      disks: [{ brand: 'ATA', device: 'sda', type: 'SSD' }],
      size: 120034123776,
    },
    {
      disks: [{ brand: 'Western Digital', device: 'sdb', type: 'HD' }],
      size: 4000787030016,
    },
  ],
  output: [-1, 20198055936, 1478133694464],
} as any as TestCase;

// https://github.com/MauriceNino/dashdot/issues/883
export const TEST_CASE_21 = {
  disks: [
    {
      device: '/dev/sda',
      type: 'HD',
      name: 'ST2000LM015-2E81',
      vendor: 'Seagate',
      size: 2000398934016,
      bytesPerSector: null,
      totalCylinders: null,
      totalHeads: null,
      totalSectors: null,
      totalTracks: null,
      tracksPerCylinder: null,
      sectorsPerTrack: null,
      firmwareRevision: '0001',
      serialNum: '',
      interfaceType: 'SATA',
      smartStatus: 'unknown',
      temperature: null,
    },
    {
      device: '/dev/nvme0n1',
      type: 'NVMe',
      name: 'Lexar SSD NM620 512GB                   ',
      vendor: '',
      size: 512110190592,
      bytesPerSector: null,
      totalCylinders: null,
      totalHeads: null,
      totalSectors: null,
      totalTracks: null,
      tracksPerCylinder: null,
      sectorsPerTrack: null,
      firmwareRevision: '',
      serialNum: 'NB1824R006843P1110',
      interfaceType: 'PCIe',
      smartStatus: 'unknown',
      temperature: null,
    },
  ],
  sizes: [
    {
      fs: 'overlay',
      type: 'overlay',
      size: 500235124736,
      used: 19390722048,
      available: 459379527680,
      use: 4.05,
      mount: '/',
      rw: false,
    },
    {
      fs: '/dev/mapper/ubuntu--vg-ubuntu--lv',
      type: 'ext4',
      size: 500235124736,
      used: 19390722048,
      available: 459379527680,
      use: 4.05,
      mount: '/mnt/host',
      rw: true,
    },
    {
      fs: '/dev/loop0',
      type: 'squashfs',
      size: 66453504,
      used: 66453504,
      available: 0,
      use: 100,
      mount: '/mnt/host/snap/core20/1822',
      rw: false,
    },
    {
      fs: '/dev/loop1',
      type: 'squashfs',
      size: 66584576,
      used: 66584576,
      available: 0,
      use: 100,
      mount: '/mnt/host/snap/core20/1974',
      rw: false,
    },
    {
      fs: '/dev/loop2',
      type: 'squashfs',
      size: 117440512,
      used: 117440512,
      available: 0,
      use: 100,
      mount: '/mnt/host/snap/lxd/24322',
      rw: false,
    },
    {
      fs: '/dev/loop3',
      type: 'squashfs',
      size: 52297728,
      used: 52297728,
      available: 0,
      use: 100,
      mount: '/mnt/host/snap/snapd/18357',
      rw: false,
    },
    {
      fs: '/dev/loop4',
      type: 'squashfs',
      size: 55967744,
      used: 55967744,
      available: 0,
      use: 100,
      mount: '/mnt/host/snap/snapd/19457',
      rw: false,
    },
    {
      fs: '/dev/nvme0n1p2',
      type: 'ext4',
      size: 2040373248,
      used: 137105408,
      available: 1779118080,
      use: 7.15,
      mount: '/mnt/host/boot',
      rw: true,
    },
    {
      fs: '/dev/nvme0n1p1',
      type: 'vfat',
      size: 1124999168,
      used: 6365184,
      available: 1118633984,
      use: 0.57,
      mount: '/mnt/host/boot/efi',
      rw: true,
    },
    {
      fs: '/dev/sda2',
      type: 'fuseblk',
      size: 2000381014016,
      used: 845375959040,
      available: 1155005054976,
      use: 42.26,
      mount: '/mnt/host/mnt/hdd1',
      rw: true,
    },
  ],
  blocks: [
    {
      name: 'nvme0n1',
      type: 'disk',
      fsType: '',
      mount: '',
      size: 512110190592,
      physical: 'SSD',
      uuid: '',
      label: '',
      model: 'Lexar SSD NM620 512GB',
      serial: 'NB1824R006843P1110  ',
      removable: false,
      protocol: 'nvme',
      group: '',
      device: '/dev/nvme0n1',
    },
    {
      name: 'sda',
      type: 'disk',
      fsType: '',
      mount: '',
      size: 2000398934016,
      physical: 'HDD',
      uuid: '',
      label: '',
      model: 'ST2000LM015-2E81',
      serial: '',
      removable: false,
      protocol: 'sata',
      group: '',
      device: '/dev/sda',
    },
    {
      name: 'loop0',
      type: 'loop',
      fsType: 'squashfs',
      mount: '/mnt/host/snap/core20/1822',
      size: 66355200,
      physical: '',
      uuid: '',
      label: '',
      model: '',
      serial: '',
      removable: false,
      protocol: '',
      group: '',
    },
    {
      name: 'loop1',
      type: 'loop',
      fsType: 'squashfs',
      mount: '/mnt/host/snap/core20/1974',
      size: 66531328,
      physical: '',
      uuid: '',
      label: '',
      model: '',
      serial: '',
      removable: false,
      protocol: '',
      group: '',
    },
    {
      name: 'loop2',
      type: 'loop',
      fsType: 'squashfs',
      mount: '/mnt/host/snap/lxd/24322',
      size: 117387264,
      physical: '',
      uuid: '',
      label: '',
      model: '',
      serial: '',
      removable: false,
      protocol: '',
      group: '',
    },
    {
      name: 'loop3',
      type: 'loop',
      fsType: 'squashfs',
      mount: '/mnt/host/snap/snapd/18357',
      size: 52260864,
      physical: '',
      uuid: '',
      label: '',
      model: '',
      serial: '',
      removable: false,
      protocol: '',
      group: '',
    },
    {
      name: 'loop4',
      type: 'loop',
      fsType: 'squashfs',
      mount: '/mnt/host/snap/snapd/19457',
      size: 55844864,
      physical: '',
      uuid: '',
      label: '',
      model: '',
      serial: '',
      removable: false,
      protocol: '',
      group: '',
    },
    {
      name: 'nvme0n1p1',
      type: 'part',
      fsType: 'vfat',
      mount: '/mnt/host/boot/efi',
      size: 1127219200,
      physical: '',
      uuid: '8EC6-F051',
      label: '',
      model: '',
      serial: '',
      removable: false,
      protocol: 'nvme',
      group: '',
      device: '/dev/nvme0n1',
    },
    {
      name: 'nvme0n1p2',
      type: 'part',
      fsType: 'ext4',
      mount: '/mnt/host/boot',
      size: 2147483648,
      physical: '',
      uuid: '70adf859-0afe-418f-8a8d-d2666e1588ad',
      label: '',
      model: '',
      serial: '',
      removable: false,
      protocol: 'nvme',
      group: '',
      device: '/dev/nvme0n1',
    },
    {
      name: 'nvme0n1p3',
      type: 'part',
      fsType: 'LVM2_member',
      mount: '',
      size: 508833038336,
      physical: '',
      uuid: '5OLVTB-oHLe-Fw0C-YtTV-758n-uuOb-82Vn3K',
      label: '',
      model: '',
      serial: '',
      removable: false,
      protocol: 'nvme',
      group: '',
      device: '/dev/nvme0n1',
    },
    {
      name: 'sda1',
      type: 'part',
      fsType: '',
      mount: '',
      size: 16759808,
      physical: '',
      uuid: '',
      label: '',
      model: '',
      serial: '',
      removable: false,
      protocol: '',
      group: '',
      device: '/dev/sda',
    },
  ],
  layout: [
    {
      disks: [{ brand: '', device: 'nvme0n1', type: 'NVMe' }],
      size: 512110190592,
    },
    {
      disks: [{ brand: 'Seagate', device: 'sda', type: 'HD' }],
      size: 2000398934016,
    },
  ],
  output: [19534192640, 845393879040],
} as any as TestCase;

// Currently somewhat incorrect due to BTRFS Raid not correctly supported
// https://github.com/MauriceNino/dashdot/issues/980
export const TEST_CASE_22 = {
  disks: [
    {
      device: '/dev/sda',
      type: 'HD',
      name: 'WDC WD181KFGX-68',
      vendor: 'Western Digital',
      size: 18000207937536,
      bytesPerSector: null,
      totalCylinders: null,
      totalHeads: null,
      totalSectors: null,
      totalTracks: null,
      tracksPerCylinder: null,
      sectorsPerTrack: null,
      firmwareRevision: '0A83',
      serialNum: '',
      interfaceType: 'SATA',
      smartStatus: 'unknown',
      temperature: null,
    },
    {
      device: '/dev/sdb',
      type: 'HD',
      name: 'WDC WD181KFGX-68',
      vendor: 'Western Digital',
      size: 18000207937536,
      bytesPerSector: null,
      totalCylinders: null,
      totalHeads: null,
      totalSectors: null,
      totalTracks: null,
      tracksPerCylinder: null,
      sectorsPerTrack: null,
      firmwareRevision: '0A83',
      serialNum: '',
      interfaceType: 'SATA',
      smartStatus: 'unknown',
      temperature: null,
    },
    {
      device: '/dev/sdc',
      type: 'HD',
      name: 'WDC WD181KFGX-68',
      vendor: 'Western Digital',
      size: 18000207937536,
      bytesPerSector: null,
      totalCylinders: null,
      totalHeads: null,
      totalSectors: null,
      totalTracks: null,
      tracksPerCylinder: null,
      sectorsPerTrack: null,
      firmwareRevision: '0A83',
      serialNum: '',
      interfaceType: 'SATA',
      smartStatus: 'unknown',
      temperature: null,
    },
    {
      device: '/dev/sdd',
      type: 'HD',
      name: 'WDC WD181KFGX-68',
      vendor: 'Western Digital',
      size: 18000207937536,
      bytesPerSector: null,
      totalCylinders: null,
      totalHeads: null,
      totalSectors: null,
      totalTracks: null,
      tracksPerCylinder: null,
      sectorsPerTrack: null,
      firmwareRevision: '0A83',
      serialNum: '',
      interfaceType: 'SATA',
      smartStatus: 'unknown',
      temperature: null,
    },
    {
      device: '/dev/nvme0n1',
      type: 'NVMe',
      name: 'Samsung SSD 980 PRO 2TB                 ',
      vendor: 'Samsung',
      size: 2000398934016,
      bytesPerSector: null,
      totalCylinders: null,
      totalHeads: null,
      totalSectors: null,
      totalTracks: null,
      tracksPerCylinder: null,
      sectorsPerTrack: null,
      firmwareRevision: '',
      serialNum: 'S6B0NL0T615860L',
      interfaceType: 'PCIe',
      smartStatus: 'unknown',
      temperature: null,
    },
  ],
  sizes: [
    {
      fs: '/dev/nvme0n1p3',
      type: 'btrfs',
      size: 1998694907904,
      used: 236039712768,
      available: 1760865275904,
      use: 11.82,
      mount: '/',
      rw: true,
    },
    {
      fs: 'efivarfs',
      type: 'efivarfs',
      size: 262144,
      used: 54272,
      available: 202752,
      use: 21.12,
      mount: '/mnt/host/sys/firmware/efi/efivars',
      rw: false,
    },
    {
      fs: '/dev/nvme0n1p2',
      type: 'ext4',
      size: 1020702720,
      used: 388988928,
      available: 561250304,
      use: 40.94,
      mount: '/mnt/host/boot',
      rw: true,
    },
    {
      fs: '/dev/nvme0n1p1',
      type: 'vfat',
      size: 627900416,
      used: 18206720,
      available: 609693696,
      use: 2.9,
      mount: '/mnt/host/boot/efi',
      rw: true,
    },
    {
      fs: '/dev/sdc1',
      type: 'btrfs',
      size: 72000827555840,
      used: 51600711196672,
      available: 2409158074368,
      use: 95.54,
      mount: '/mnt/host/mnt/cryo',
      rw: true,
    },
  ],
  blocks: [
    {
      name: 'nvme0n1',
      type: 'disk',
      fsType: '',
      mount: '',
      size: 2000398934016,
      physical: 'SSD',
      uuid: '',
      label: '',
      model: 'Samsung SSD 980 PRO 2TB',
      serial: 'S6B0NL0T615860L     ',
      removable: false,
      protocol: 'nvme',
      group: '',
      device: '/dev/nvme0n1',
    },
    {
      name: 'sda',
      type: 'disk',
      fsType: 'btrfs',
      mount: '',
      size: 18000207937536,
      physical: 'HDD',
      uuid: 'a5850a6f-adba-4e34-8fe4-6f191813d5cd',
      label: '',
      model: 'WDC WD181KFGX-68',
      serial: '',
      removable: false,
      protocol: 'sata',
      group: '',
      device: '/dev/sda',
    },
    {
      name: 'sdb',
      type: 'disk',
      fsType: 'btrfs',
      mount: '',
      size: 18000207937536,
      physical: 'HDD',
      uuid: 'a5850a6f-adba-4e34-8fe4-6f191813d5cd',
      label: '',
      model: 'WDC WD181KFGX-68',
      serial: '',
      removable: false,
      protocol: 'sata',
      group: '',
      device: '/dev/sdb',
    },
    {
      name: 'sdc',
      type: 'disk',
      fsType: '',
      mount: '',
      size: 18000207937536,
      physical: 'HDD',
      uuid: '',
      label: '',
      model: 'WDC WD181KFGX-68',
      serial: '',
      removable: false,
      protocol: 'sata',
      group: '',
      device: '/dev/sdc',
    },
    {
      name: 'sdd',
      type: 'disk',
      fsType: '',
      mount: '',
      size: 18000207937536,
      physical: 'HDD',
      uuid: '',
      label: '',
      model: 'WDC WD181KFGX-68',
      serial: '',
      removable: false,
      protocol: 'sata',
      group: '',
      device: '/dev/sdd',
    },
    {
      name: 'zram0',
      type: 'disk',
      fsType: 'swap',
      mount: '[SWAP]',
      size: 8589934592,
      physical: 'SSD',
      uuid: '7bcab061-21a3-4241-b6e3-bfe482fa018d',
      label: 'zram0',
      model: '',
      serial: '',
      removable: false,
      protocol: '',
      group: '',
      device: '/dev/zram0',
    },
    {
      name: 'nvme0n1p1',
      type: 'part',
      fsType: 'vfat',
      mount: '/mnt/host/boot/efi',
      size: 629145600,
      physical: '',
      uuid: '3671-6189',
      label: '',
      model: '',
      serial: '',
      removable: false,
      protocol: 'nvme',
      group: '',
      device: '/dev/nvme0n1',
    },
    {
      name: 'nvme0n1p2',
      type: 'part',
      fsType: 'ext4',
      mount: '/mnt/host/boot',
      size: 1073741824,
      physical: '',
      uuid: '7b45994d-fe45-406d-b7f8-1ec605f6dcd7',
      label: '',
      model: '',
      serial: '',
      removable: false,
      protocol: 'nvme',
      group: '',
      device: '/dev/nvme0n1',
    },
    {
      name: 'nvme0n1p3',
      type: 'part',
      fsType: 'btrfs',
      mount: '/etc/hosts',
      size: 1998694907904,
      physical: '',
      uuid: 'b795618d-1f46-4658-b196-69c7d4348e40',
      label: 'fedora_localhost-live',
      model: '',
      serial: '',
      removable: false,
      protocol: 'nvme',
      group: '',
      device: '/dev/nvme0n1',
    },
    {
      name: 'sdc1',
      type: 'part',
      fsType: 'btrfs',
      mount: '/mnt/host/mnt/cryo',
      size: 18000205840384,
      physical: '',
      uuid: 'a5850a6f-adba-4e34-8fe4-6f191813d5cd',
      label: '',
      model: '',
      serial: '',
      removable: false,
      protocol: '',
      group: '',
      device: '/dev/sdc',
    },
    {
      name: 'sdd1',
      type: 'part',
      fsType: 'btrfs',
      mount: '',
      size: 18000205840384,
      physical: '',
      uuid: 'a5850a6f-adba-4e34-8fe4-6f191813d5cd',
      label: '',
      model: '',
      serial: '',
      removable: false,
      protocol: '',
      group: '',
      device: '/dev/sdd',
    },
  ],
  layout: [
    {
      disks: [{ brand: 'Samsung', device: 'nvme0n1', type: 'NVMe' }],
      size: 2000398934016,
    },
    {
      disks: [{ brand: 'Western Digital', device: 'sdc', type: 'HD' }],
      size: 18000207937536,
    },
  ],
  output: [1999157526528, 51600711196672],
} as any as TestCase;

// Demo server (dash.mauz.dev)
export const TEST_CASE_23 = {
  disks: [
    {
      device: '/dev/sda',
      type: 'HD',
      name: 'QEMU HARDDISK   ',
      vendor: 'QEMU',
      size: 429496729600,
      bytesPerSector: null,
      totalCylinders: null,
      totalHeads: null,
      totalSectors: null,
      totalTracks: null,
      tracksPerCylinder: null,
      sectorsPerTrack: null,
      firmwareRevision: '2.5+',
      serialNum: '',
      interfaceType: '',
      smartStatus: 'unknown',
      temperature: null,
    },
  ],
  sizes: [
    {
      fs: 'overlay',
      type: 'overlay',
      size: 416055988224,
      used: 267272163328,
      available: 148767047680,
      use: 64.24,
      mount: '/',
      rw: false,
    },
    {
      fs: '/dev/sda1',
      type: 'ext4',
      size: 416055988224,
      used: 267272163328,
      available: 148767047680,
      use: 64.24,
      mount: '/mnt/host',
      rw: true,
    },
    {
      fs: '/dev/loop1',
      type: 'squashfs',
      size: 66584576,
      used: 66584576,
      available: 0,
      use: 100,
      mount: '/mnt/host/snap/core20/2015',
      rw: false,
    },
    {
      fs: '/dev/loop3',
      type: 'squashfs',
      size: 77594624,
      used: 77594624,
      available: 0,
      use: 100,
      mount: '/mnt/host/snap/core22/864',
      rw: false,
    },
    {
      fs: '/dev/sda15',
      type: 'vfat',
      size: 109422592,
      used: 6334464,
      available: 103089152,
      use: 5.79,
      mount: '/mnt/host/boot/efi',
      rw: true,
    },
    {
      fs: '/dev/loop5',
      type: 'squashfs',
      size: 42860544,
      used: 42860544,
      available: 0,
      use: 100,
      mount: '/mnt/host/snap/snapd/20290',
      rw: false,
    },
    {
      fs: '/dev/loop8',
      type: 'squashfs',
      size: 159514624,
      used: 159514624,
      available: 0,
      use: 100,
      mount: '/mnt/host/snap/lxd/26093',
      rw: false,
    },
    {
      fs: '/dev/loop4',
      type: 'squashfs',
      size: 159514624,
      used: 159514624,
      available: 0,
      use: 100,
      mount: '/mnt/host/snap/lxd/26200',
      rw: false,
    },
    {
      fs: '/dev/loop6',
      type: 'squashfs',
      size: 77725696,
      used: 77725696,
      available: 0,
      use: 100,
      mount: '/mnt/host/snap/core22/1033',
      rw: false,
    },
    {
      fs: '/dev/loop2',
      type: 'squashfs',
      size: 67108864,
      used: 67108864,
      available: 0,
      use: 100,
      mount: '/mnt/host/snap/core20/2105',
      rw: false,
    },
    {
      fs: '/dev/loop0',
      type: 'squashfs',
      size: 42467328,
      used: 42467328,
      available: 0,
      use: 100,
      mount: '/mnt/host/snap/snapd/20671',
      rw: false,
    },
  ],
  blocks: [
    {
      name: 'sda',
      type: 'disk',
      fsType: '',
      mount: '',
      size: 429496729600,
      physical: 'HDD',
      uuid: '',
      label: '',
      model: 'QEMU HARDDISK',
      serial: '',
      removable: false,
      protocol: '',
      group: '',
      device: '/dev/sda',
    },
    {
      name: 'loop0',
      type: 'loop',
      fsType: 'squashfs',
      mount: '/mnt/host/snap/snapd/20671',
      size: 42393600,
      physical: '',
      uuid: '',
      label: '',
      model: '',
      serial: '',
      removable: false,
      protocol: '',
      group: '',
    },
    {
      name: 'loop1',
      type: 'loop',
      fsType: 'squashfs',
      mount: '/mnt/host/snap/core20/2015',
      size: 66547712,
      physical: '',
      uuid: '',
      label: '',
      model: '',
      serial: '',
      removable: false,
      protocol: '',
      group: '',
    },
    {
      name: 'loop2',
      type: 'loop',
      fsType: 'squashfs',
      mount: '/mnt/host/snap/core20/2105',
      size: 67014656,
      physical: '',
      uuid: '',
      label: '',
      model: '',
      serial: '',
      removable: false,
      protocol: '',
      group: '',
    },
    {
      name: 'loop3',
      type: 'loop',
      fsType: 'squashfs',
      mount: '/mnt/host/snap/core22/864',
      size: 77492224,
      physical: '',
      uuid: '',
      label: '',
      model: '',
      serial: '',
      removable: false,
      protocol: '',
      group: '',
    },
    {
      name: 'loop4',
      type: 'loop',
      fsType: 'squashfs',
      mount: '/mnt/host/snap/lxd/26200',
      size: 159444992,
      physical: '',
      uuid: '',
      label: '',
      model: '',
      serial: '',
      removable: false,
      protocol: '',
      group: '',
    },
    {
      name: 'loop5',
      type: 'loop',
      fsType: 'squashfs',
      mount: '/mnt/host/snap/snapd/20290',
      size: 42840064,
      physical: '',
      uuid: '',
      label: '',
      model: '',
      serial: '',
      removable: false,
      protocol: '',
      group: '',
    },
    {
      name: 'loop6',
      type: 'loop',
      fsType: 'squashfs',
      mount: '/mnt/host/snap/core22/1033',
      size: 77713408,
      physical: '',
      uuid: '',
      label: '',
      model: '',
      serial: '',
      removable: false,
      protocol: '',
      group: '',
    },
    {
      name: 'loop7',
      type: 'loop',
      fsType: 'squashfs',
      mount: '',
      size: 42827776,
      physical: '',
      uuid: '',
      label: '',
      model: '',
      serial: '',
      removable: false,
      protocol: '',
      group: '',
    },
    {
      name: 'loop8',
      type: 'loop',
      fsType: 'squashfs',
      mount: '/mnt/host/snap/lxd/26093',
      size: 159514624,
      physical: '',
      uuid: '',
      label: '',
      model: '',
      serial: '',
      removable: false,
      protocol: '',
      group: '',
    },
    {
      name: 'sda1',
      type: 'part',
      fsType: 'ext4',
      mount: '/mnt/host',
      size: 429380320768,
      physical: '',
      uuid: '43d2b5d9-3af2-48e8-908f-9b975e8974d6',
      label: 'cloudimg-rootfs',
      model: '',
      serial: '',
      removable: false,
      protocol: '',
      group: '',
      device: '/dev/sda',
    },
    {
      name: 'sda14',
      type: 'part',
      fsType: '',
      mount: '',
      size: 4194304,
      physical: '',
      uuid: '',
      label: '',
      model: '',
      serial: '',
      removable: false,
      protocol: '',
      group: '',
      device: '/dev/sda',
    },
    {
      name: 'sda15',
      type: 'part',
      fsType: 'vfat',
      mount: '/mnt/host/boot/efi',
      size: 111149056,
      physical: '',
      uuid: '9DDD-AECA',
      label: 'UEFI',
      model: '',
      serial: '',
      removable: false,
      protocol: '',
      group: '',
      device: '/dev/sda',
    },
  ],
  layout: [
    {
      disks: [{ brand: 'QEMU', device: 'sda', type: 'HD' }],
      size: 429496729600,
    },
  ],
  output: [280609816576],
} as any as TestCase;

// Test case from home server
export const TEST_CASE_24 = {
  disks: [
    {
      device: '/dev/nvme0n1',
      type: 'NVMe',
      name: 'PCIe SSD                                ',
      vendor: '',
      size: 512110190592,
      bytesPerSector: null,
      totalCylinders: null,
      totalHeads: null,
      totalSectors: null,
      totalTracks: null,
      tracksPerCylinder: null,
      sectorsPerTrack: null,
      firmwareRevision: '',
      serialNum: '7FBC07390DD900365059',
      interfaceType: 'PCIe',
      smartStatus: 'unknown',
      temperature: null,
    },
  ],
  sizes: [
    {
      fs: 'overlay',
      type: 'overlay',
      size: 105089261568,
      used: 11768532992,
      available: 87935242240,
      use: 11.8,
      mount: '/',
      rw: false,
    },
    {
      fs: '/dev/mapper/ubuntu--vg-ubuntu--lv',
      type: 'ext4',
      size: 105089261568,
      used: 11768532992,
      available: 87935242240,
      use: 11.8,
      mount: '/mnt/host',
      rw: true,
    },
    {
      fs: '/dev/loop0',
      type: 'squashfs',
      size: 66584576,
      used: 66584576,
      available: 0,
      use: 100,
      mount: '/mnt/host/snap/core20/1974',
      rw: false,
    },
    {
      fs: '/dev/loop1',
      type: 'squashfs',
      size: 117440512,
      used: 117440512,
      available: 0,
      use: 100,
      mount: '/mnt/host/snap/lxd/24322',
      rw: false,
    },
    {
      fs: '/dev/loop2',
      type: 'squashfs',
      size: 55967744,
      used: 55967744,
      available: 0,
      use: 100,
      mount: '/mnt/host/snap/snapd/19457',
      rw: false,
    },
    {
      fs: '/dev/nvme0n1p2',
      type: 'ext4',
      size: 2040373248,
      used: 136232960,
      available: 1779990528,
      use: 7.11,
      mount: '/mnt/host/boot',
      rw: true,
    },
    {
      fs: '/dev/nvme0n1p1',
      type: 'vfat',
      size: 1124999168,
      used: 6369280,
      available: 1118629888,
      use: 0.57,
      mount: '/mnt/host/boot/efi',
      rw: true,
    },
  ],
  blocks: [
    {
      name: 'nvme0n1',
      type: 'disk',
      fsType: '',
      mount: '',
      size: 512110190592,
      physical: 'SSD',
      uuid: '',
      label: '',
      model: 'PCIe SSD',
      serial: '7FBC07390DD900365059',
      removable: false,
      protocol: 'nvme',
      group: '',
      device: '/dev/nvme0n1',
    },
    {
      name: 'loop0',
      type: 'loop',
      fsType: 'squashfs',
      mount: '/mnt/host/snap/core20/1974',
      size: 66531328,
      physical: '',
      uuid: '',
      label: '',
      model: '',
      serial: '',
      removable: false,
      protocol: '',
      group: '',
    },
    {
      name: 'loop1',
      type: 'loop',
      fsType: 'squashfs',
      mount: '/mnt/host/snap/lxd/24322',
      size: 117387264,
      physical: '',
      uuid: '',
      label: '',
      model: '',
      serial: '',
      removable: false,
      protocol: '',
      group: '',
    },
    {
      name: 'loop2',
      type: 'loop',
      fsType: 'squashfs',
      mount: '/mnt/host/snap/snapd/19457',
      size: 55844864,
      physical: '',
      uuid: '',
      label: '',
      model: '',
      serial: '',
      removable: false,
      protocol: '',
      group: '',
    },
    {
      name: 'nvme0n1p1',
      type: 'part',
      fsType: 'vfat',
      mount: '/mnt/host/boot/efi',
      size: 1127219200,
      physical: '',
      uuid: '060E-D169',
      label: '',
      model: '',
      serial: '',
      removable: false,
      protocol: 'nvme',
      group: '',
      device: '/dev/nvme0n1',
    },
    {
      name: 'nvme0n1p2',
      type: 'part',
      fsType: 'ext4',
      mount: '/mnt/host/boot',
      size: 2147483648,
      physical: '',
      uuid: 'dc87bf05-b396-43cb-a967-063d9a4c0466',
      label: '',
      model: '',
      serial: '',
      removable: false,
      protocol: 'nvme',
      group: '',
      device: '/dev/nvme0n1',
    },
    {
      name: 'nvme0n1p3',
      type: 'part',
      fsType: 'LVM2_member',
      mount: '',
      size: 508833038336,
      physical: '',
      uuid: 'YVRqdg-O2wM-Xt1P-u9mk-wtWW-7G56-S5ZFKR',
      label: '',
      model: '',
      serial: '',
      removable: false,
      protocol: 'nvme',
      group: '',
      device: '/dev/nvme0n1',
    },
  ],
  layout: [
    {
      disks: [{ brand: '', device: 'nvme0n1', type: 'NVMe' }],
      size: 512110190592,
    },
  ],
  output: [11911135232],
} as any as TestCase;

// https://github.com/MauriceNino/dashdot/issues/1008#issuecomment-1898024021
export const TEST_CASE_25 = {
  disks: [
    {
      device: '/dev/sda',
      type: 'SSD',
      name: 'K2              ',
      vendor: 'ATA',
      size: 120034123776,
      bytesPerSector: null,
      totalCylinders: null,
      totalHeads: null,
      totalSectors: null,
      totalTracks: null,
      tracksPerCylinder: null,
      sectorsPerTrack: null,
      firmwareRevision: '0807',
      serialNum: '',
      interfaceType: 'SATA',
      smartStatus: 'unknown',
      temperature: null,
    },
    {
      device: '/dev/sdb',
      type: 'HD',
      name: 'USB 3.0 Destop H',
      vendor: 'ASMT',
      size: 1000204886016,
      bytesPerSector: null,
      totalCylinders: null,
      totalHeads: null,
      totalSectors: null,
      totalTracks: null,
      tracksPerCylinder: null,
      sectorsPerTrack: null,
      firmwareRevision: '0',
      serialNum: '',
      interfaceType: 'USB',
      smartStatus: 'unknown',
      temperature: null,
    },
  ],
  sizes: [
    {
      fs: 'overlay',
      type: 'overlay',
      size: 116541034496,
      used: 39132753920,
      available: 71441047552,
      use: 35.39,
      mount: '/',
      rw: false,
    },
    {
      fs: '/dev/sda1',
      type: 'ext4',
      size: 116541034496,
      used: 39132753920,
      available: 71441047552,
      use: 35.39,
      mount: '/mnt/host',
      rw: true,
    },
    {
      fs: 'systemd-1',
      type: 'autofs',
      size: 983351140352,
      used: 745736282112,
      available: 187587837952,
      use: 79.9,
      mount: '/mnt/host/media/usb',
      rw: false,
    },
    {
      fs: '/dev/sdb',
      type: 'ext4',
      size: 983351140352,
      used: 745736282112,
      available: 187587837952,
      use: 79.9,
      mount: '/mnt/host/media/usb',
      rw: true,
    },
  ],
  blocks: [
    {
      name: 'sda',
      type: 'disk',
      fsType: '',
      mount: '',
      size: 120034123776,
      physical: 'SSD',
      uuid: '',
      label: '',
      model: 'K2',
      serial: '',
      removable: false,
      protocol: 'sata',
      group: '',
      device: '/dev/sda',
    },
    {
      name: 'sdb',
      type: 'disk',
      fsType: 'ext4',
      mount: '/mnt/host/media/usb',
      size: 1000204886016,
      physical: 'HDD',
      uuid: '34a8cfcd-35fd-4797-ac43-69c1f176762a',
      label: '',
      model: 'USB 3.0 Destop H',
      serial: '',
      removable: false,
      protocol: 'usb',
      group: '',
      device: '/dev/sdb',
    },
    {
      name: 'sda1',
      type: 'part',
      fsType: 'ext4',
      mount: '/mnt/host',
      size: 119009181696,
      physical: '',
      uuid: '3a3a6d61-726f-475f-a9b1-f028b3814021',
      label: '',
      model: '',
      serial: '',
      removable: false,
      protocol: '',
      group: '',
      device: '/dev/sda',
    },
    {
      name: 'sda2',
      type: 'part',
      fsType: '',
      mount: '',
      size: 1024,
      physical: '',
      uuid: '',
      label: '',
      model: '',
      serial: '',
      removable: false,
      protocol: '',
      group: '',
      device: '/dev/sda',
    },
    {
      name: 'sda5',
      type: 'part',
      fsType: 'swap',
      mount: '[SWAP]',
      size: 1022361600,
      physical: '',
      uuid: 'a96465f5-3925-456b-bd02-a3590c6c8179',
      label: '',
      model: '',
      serial: '',
      removable: false,
      protocol: '',
      group: '',
      device: '/dev/sda',
    },
    {
      name: 'sr0',
      type: 'rom',
      fsType: '',
      mount: '',
      size: 1073741312,
      physical: 'CD/DVD',
      uuid: '',
      label: '',
      model: 'DVD-RW DU8AESH',
      serial: '',
      removable: true,
      protocol: 'usb',
      group: '',
    },
  ],
  layout: [
    {
      disks: [{ brand: 'ATA', device: 'sda', type: 'SSD' }],
      size: 120034123776,
    },
    {
      disks: [{ brand: 'ASMT', device: 'sdb', type: 'HD' }],
      size: 1000204886016,
    },
  ],
  output: [42625843200, 762590027776],
} as any as TestCase;

// Test case from home server (with external disk)
export const TEST_CASE_26 = {
  disks: [
    {
      device: '/dev/sda',
      type: 'HD',
      name: 'Portable        ',
      vendor: 'Seagate',
      size: 4000787029504,
      bytesPerSector: null,
      totalCylinders: null,
      totalHeads: null,
      totalSectors: null,
      totalTracks: null,
      tracksPerCylinder: null,
      sectorsPerTrack: null,
      firmwareRevision: '0712',
      serialNum: '',
      interfaceType: 'USB',
      smartStatus: 'unknown',
      temperature: null,
    },
    {
      device: '/dev/nvme0n1',
      type: 'NVMe',
      name: 'PCIe SSD                                ',
      vendor: '',
      size: 512110190592,
      bytesPerSector: null,
      totalCylinders: null,
      totalHeads: null,
      totalSectors: null,
      totalTracks: null,
      tracksPerCylinder: null,
      sectorsPerTrack: null,
      firmwareRevision: '',
      serialNum: '7FBC07390DD900365059',
      interfaceType: 'PCIe',
      smartStatus: 'unknown',
      temperature: null,
    },
  ],
  sizes: [
    {
      fs: 'overlay',
      type: 'overlay',
      size: 105089261568,
      used: 41106567168,
      available: 58597208064,
      use: 41.23,
      mount: '/',
      rw: false,
    },
    {
      fs: '/dev/mapper/ubuntu--vg-ubuntu--lv',
      type: 'ext4',
      size: 105089261568,
      used: 41106567168,
      available: 58597208064,
      use: 41.23,
      mount: '/mnt/host',
      rw: true,
    },
    {
      fs: 'efivarfs',
      type: 'efivarfs',
      size: 196608,
      used: 92160,
      available: 99328,
      use: 48.13,
      mount: '/mnt/host/sys/firmware/efi/efivars',
      rw: false,
    },
    {
      fs: '/dev/loop0',
      type: 'squashfs',
      size: 66584576,
      used: 66584576,
      available: 0,
      use: 100,
      mount: '/mnt/host/snap/core20/1974',
      rw: false,
    },
    {
      fs: '/dev/loop1',
      type: 'squashfs',
      size: 67108864,
      used: 67108864,
      available: 0,
      use: 100,
      mount: '/mnt/host/snap/core20/2105',
      rw: false,
    },
    {
      fs: '/dev/loop2',
      type: 'squashfs',
      size: 117440512,
      used: 117440512,
      available: 0,
      use: 100,
      mount: '/mnt/host/snap/lxd/24322',
      rw: false,
    },
    {
      fs: '/dev/loop3',
      type: 'squashfs',
      size: 55967744,
      used: 55967744,
      available: 0,
      use: 100,
      mount: '/mnt/host/snap/snapd/19457',
      rw: false,
    },
    {
      fs: '/dev/loop4',
      type: 'squashfs',
      size: 42467328,
      used: 42467328,
      available: 0,
      use: 100,
      mount: '/mnt/host/snap/snapd/20671',
      rw: false,
    },
    {
      fs: '/dev/nvme0n1p2',
      type: 'ext4',
      size: 2040373248,
      used: 284254208,
      available: 1631969280,
      use: 14.83,
      mount: '/mnt/host/boot',
      rw: false,
    },
    {
      fs: '/dev/nvme0n1p1',
      type: 'vfat',
      size: 1124999168,
      used: 6369280,
      available: 1118629888,
      use: 0.57,
      mount: '/mnt/host/boot/efi',
      rw: false,
    },
    {
      fs: '/dev/sda1',
      type: 'ext4',
      size: 3936820690944,
      used: 1772756307968,
      available: 1964008259584,
      use: 47.44,
      mount: '/mnt/host/mnt/media',
      rw: false,
    },
  ],
  blocks: [
    {
      name: 'nvme0n1',
      type: 'disk',
      fsType: '',
      mount: '',
      size: 512110190592,
      physical: 'SSD',
      uuid: '',
      label: '',
      model: 'PCIe SSD',
      serial: '7FBC07390DD900365059',
      removable: false,
      protocol: 'nvme',
      group: '',
      device: '/dev/nvme0n1',
    },
    {
      name: 'sda',
      type: 'disk',
      fsType: '',
      mount: '',
      size: 4000787029504,
      physical: 'HDD',
      uuid: '',
      label: '',
      model: 'Portable',
      serial: '',
      removable: false,
      protocol: 'usb',
      group: '',
      device: '/dev/sda',
    },
    {
      name: 'loop0',
      type: 'loop',
      fsType: 'squashfs',
      mount: '/mnt/host/snap/core20/1974',
      size: 66531328,
      physical: '',
      uuid: '',
      label: '',
      model: '',
      serial: '',
      removable: false,
      protocol: '',
      group: '',
    },
    {
      name: 'loop1',
      type: 'loop',
      fsType: 'squashfs',
      mount: '/mnt/host/snap/core20/2105',
      size: 67014656,
      physical: '',
      uuid: '',
      label: '',
      model: '',
      serial: '',
      removable: false,
      protocol: '',
      group: '',
    },
    {
      name: 'loop2',
      type: 'loop',
      fsType: 'squashfs',
      mount: '/mnt/host/snap/lxd/24322',
      size: 117387264,
      physical: '',
      uuid: '',
      label: '',
      model: '',
      serial: '',
      removable: false,
      protocol: '',
      group: '',
    },
    {
      name: 'loop3',
      type: 'loop',
      fsType: 'squashfs',
      mount: '/mnt/host/snap/snapd/19457',
      size: 55844864,
      physical: '',
      uuid: '',
      label: '',
      model: '',
      serial: '',
      removable: false,
      protocol: '',
      group: '',
    },
    {
      name: 'loop4',
      type: 'loop',
      fsType: 'squashfs',
      mount: '/mnt/host/snap/snapd/20671',
      size: 42393600,
      physical: '',
      uuid: '',
      label: '',
      model: '',
      serial: '',
      removable: false,
      protocol: '',
      group: '',
    },
    {
      name: 'nvme0n1p1',
      type: 'part',
      fsType: 'vfat',
      mount: '/mnt/host/boot/efi',
      size: 1127219200,
      physical: '',
      uuid: '060E-D169',
      label: '',
      model: '',
      serial: '',
      removable: false,
      protocol: 'nvme',
      group: '',
      device: '/dev/nvme0n1',
    },
    {
      name: 'nvme0n1p2',
      type: 'part',
      fsType: 'ext4',
      mount: '/mnt/host/boot',
      size: 2147483648,
      physical: '',
      uuid: 'dc87bf05-b396-43cb-a967-063d9a4c0466',
      label: '',
      model: '',
      serial: '',
      removable: false,
      protocol: 'nvme',
      group: '',
      device: '/dev/nvme0n1',
    },
    {
      name: 'nvme0n1p3',
      type: 'part',
      fsType: 'LVM2_member',
      mount: '',
      size: 508833038336,
      physical: '',
      uuid: 'YVRqdg-O2wM-Xt1P-u9mk-wtWW-7G56-S5ZFKR',
      label: '',
      model: '',
      serial: '',
      removable: false,
      protocol: 'nvme',
      group: '',
      device: '/dev/nvme0n1',
    },
    {
      name: 'sda1',
      type: 'part',
      fsType: 'ext4',
      mount: '/mnt/host/mnt/media',
      size: 4000786992128,
      physical: '',
      uuid: '4a38cee0-e843-46a9-bcc4-7fdd8b29a11a',
      label: '',
      model: '',
      serial: '',
      removable: false,
      protocol: '',
      group: '',
      device: '/dev/sda',
    },
  ],
  layout: [
    {
      disks: [{ brand: '', device: 'nvme0n1', type: 'NVMe' }],
      size: 512110190592,
    },
    {
      disks: [{ brand: 'Seagate', device: 'sda', type: 'HD' }],
      size: 4000787029504,
    },
  ],
  output: [41397190656, 1836722646528],
} as any as TestCase;
