---
kind: pipeline
type: docker
name: CI

steps:
  # TESTING #
  - name: test
    image: node:lts-alpine
    when:
      event:
        - push
        - pull_request
    commands:
      - yarn --immutable --immutable-cache --check-cache
      - yarn test

  # FEATURE BUILD (LOCAL) #
  - name: build
    when:
      event:
        - push
        - pull_request
      branch:
        exclude:
          - main
          - dev
    image: node:lts-alpine
    commands:
      - yarn build

  # DEV BUILD #
  - name: build & deploy to dockerhub (dev)
    image: crazymax/docker:latest
    when:
      event: push
      branch: dev
    environment:
      DOCKER_ACCESS_KEY:
        from_secret: DOCKER_ACCESS_KEY
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    commands:
      - echo $DOCKER_ACCESS_KEY | docker login -u mauricenino --password-stdin
      - docker buildx create --name builder --driver docker-container --use
      - docker buildx inspect --bootstrap --builder builder
      - docker buildx build --platform linux/amd64 -t mauricenino/dashdot:dev -o type=registry .
      - docker logout
  - name: update & deploy server files (dev)
    image: docker/compose
    when:
      event: push
      branch: dev
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
      - name: server
        path: /server
    commands:
      - docker image pull mauricenino/dashdot:dev
      - cd /server && ./start.sh dashdot

  # PROD BUILD #
  - name: build & deploy to dockerhub (production)
    image: crazymax/docker:latest
    when:
      event: push
      branch: main
    environment:
      DOCKER_ACCESS_KEY:
        from_secret: DOCKER_ACCESS_KEY
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    commands:
      - |
        sed 's/.*"version": "\(.*\)".*/\1/;t;d' ./package.json > package.version
      - echo $DOCKER_ACCESS_KEY | docker login -u mauricenino --password-stdin
      - docker buildx create --name builder --driver docker-container --use
      - docker buildx inspect --bootstrap --builder builder
      - docker buildx build --platform linux/amd64,linux/arm/v7,linux/arm64/v8 -t mauricenino/dashdot:latest -t mauricenino/dashdot:$(cat package.version) -o type=registry .
      - docker logout
  - name: update & deploy server files
    image: docker/compose
    when:
      event: push
      branch: main
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
      - name: server
        path: /server
    commands:
      - docker image pull mauricenino/dashdot:latest
      - cd /server && ./start.sh dashdot

  # CREATE RELEASE NOTES #
  - name: create release notes
    image: timbru31/node-alpine-git:latest
    when:
      event: tag
    environment:
      GITHUB_TOKEN:
        from_secret: GITHUB_TOKEN
    commands:
      - yarn --immutable --immutable-cache
      - yarn semantic-release

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock
  - name: server
    host:
      path: /server

---
kind: secret
name: DOCKER_ACCESS_KEY
data: ysbzIhceuQjxnBZ7kRt63CswtG85WTCiCBFPCM8wmV9qBQTS9kGPktIqw1wevm1O0U2l1pTWl7wt2e7D+a462Q==
---
kind: secret
name: GITHUB_TOKEN
data: JMpZE0aC5Fau1tDEh+6Huy+yZJF1BqhVAzIm7+Xvfx9vYxHRrPAbh6hZrJzEvEjK9ClGNoPCHJaKmezV3Yrt2qYsARU=
---
kind: signature
hmac: 5a3e107e7097eaee6a77634b060db420033fbe33c12e8b9a46cc9f62ae4982da
