---
kind: pipeline
type: docker
name: CI

trigger:
  event:
    exclude:
      - tag

steps:
  # DEPENDENCIES #
  - name: dependencies
    image: timbru31/node-alpine-git:latest
    when:
      event:
        - push
        - custom
    commands:
      - yarn --immutable --immutable-cache
  - name: dependencies (pr)
    image: timbru31/node-alpine-git:latest
    when:
      event:
        - pull_request
    commands:
      - yarn --immutable --immutable-cache --check-cache

  # TESTING #
  - name: test
    image: timbru31/node-alpine-git:latest
    when:
      event:
        - push
        - pull_request
        - custom
    commands:
      - yarn test

  # FEATURE BUILD (LOCAL) #
  - name: build
    when:
      event:
        - push
        - pull_request
        - custom
      branch:
        exclude:
          - main
          - dev
    image: timbru31/node-alpine-git:latest
    commands:
      - yarn build

  # DEV BUILD #
  - name: build & release (dockerhub) (dev)
    image: crazymax/docker:latest
    when:
      event:
        - push
        - custom
      branch: dev
    environment:
      DOCKER_ACCESS_KEY:
        from_secret: DOCKER_ACCESS_KEY
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    commands:
      - apk add git
      - echo $DOCKER_ACCESS_KEY | docker login -u mauricenino --password-stdin
      - docker buildx create --name builder --driver docker-container --use
      - docker buildx inspect --bootstrap --builder builder
      - docker buildx build
        --platform linux/amd64,linux/arm/v7,linux/arm64/v8
        --target prod
        --label org.opencontainers.image.title="dash."
        --label org.opencontainers.image.description="dash. - a modern server dashboard"
        --label org.opencontainers.image.authors="MauriceNino <mauriceprivat98@gmail.com>"
        --label org.opencontainers.image.url=https://github.com/MauriceNino/dashdot
        --label org.opencontainers.image.source=https://github.com/MauriceNino/dashdot
        --label org.opencontainers.image.licenses=MIT
        --build-arg VERSION=0.0.0-dev
        --build-arg BUILDHASH=$(git log -1 --format="%H")
        -o type=registry
        -t mauricenino/dashdot:dev .
  - name: update & deploy server files (dev)
    image: docker/compose
    when:
      event:
        - push
        - custom
      branch: dev
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
      - name: server
        path: /server
    commands:
      - docker image pull mauricenino/dashdot:dev
      - cd /server && ./start.sh dashdot

  # PROD BUILD #
  - name: build & release (dockerhub & github) (production)
    image: crazymax/docker:latest
    when:
      event:
        - push
        - custom
      branch: main
    environment:
      GITHUB_TOKEN:
        from_secret: GITHUB_TOKEN
      DOCKER_ACCESS_KEY:
        from_secret: DOCKER_ACCESS_KEY
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    commands:
      - apk add git nodejs yarn
      - yarn semantic-release -d | sed -n 's/.*The next release version is \([0-9]\+\.[0-9]\+\.[0-9]\+\)/\1/p' > package.version
      - 'echo "Next Version: $(cat package.version)"'
      - '[ -s package.version ] || exit 1'
      - echo $DOCKER_ACCESS_KEY | docker login -u mauricenino --password-stdin
      - docker buildx create --name builder --driver docker-container --use
      - docker buildx inspect --bootstrap --builder builder
      - docker buildx build
        --platform linux/amd64,linux/arm/v7,linux/arm64/v8
        --target prod
        --label org.opencontainers.image.title="dash."
        --label org.opencontainers.image.description="dash. - a modern server dashboard"
        --label org.opencontainers.image.authors="MauriceNino <mauriceprivat98@gmail.com>"
        --label org.opencontainers.image.url=https://github.com/MauriceNino/dashdot
        --label org.opencontainers.image.source=https://github.com/MauriceNino/dashdot
        --label org.opencontainers.image.licenses=MIT
        --build-arg VERSION=$(cat package.version)
        --build-arg BUILDHASH=$(git log -1 --format="%H")
        -o type=registry
        -t mauricenino/dashdot:$(cat package.version)
        -t mauricenino/dashdot:latest .
      - yarn semantic-release
  - name: deploy gh-pages
    image: timbru31/node-alpine-git:latest
    when:
      event:
        - push
        - custom
      branch: main
    environment:
      GIT_USER: MauriceNino
      GIT_PASS:
        from_secret: GITHUB_TOKEN
    commands:
      - yarn nx build docs
      - yarn nx deploy docs
  - name: update & deploy server files
    image: docker/compose
    when:
      event:
        - push
        - custom
      branch: main
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
      - name: server
        path: /server
    commands:
      - docker image pull mauricenino/dashdot:latest
      - cd /server && ./start.sh dashdot

  # CLEANUP #
  - name: cleanup
    image: crazymax/docker:latest
    when:
      status:
        - failure
        - success
    failure: ignore
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    commands:
      - docker logout
      - docker image rm $(docker images -f "dangling=true" | grep 'mauricenino/dashdot') || true

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock
  - name: server
    host:
      path: /server

---
kind: secret
name: DOCKER_ACCESS_KEY
data: aRlMTaj5z6fMgCnFDDiLTPakLlcziQvZxw0K8k06ZsIdeGshKPMzMhl4+UoiC4rCaDtsnu0hmcXeIzqP83NQXw==
---
kind: secret
name: GITHUB_TOKEN
data: JMpZE0aC5Fau1tDEh+6Huy+yZJF1BqhVAzIm7+Xvfx9vYxHRrPAbh6hZrJzEvEjK9ClGNoPCHJaKmezV3Yrt2qYsARU=
---
kind: signature
hmac: fb8e06b4c73d6feb3772cb8d36533c90e3f0220da5151e8d4a8d006d03b7039c
