httpTimeout: 600000
nodeLinker: node-modules
defaultSemverRangePrefix: ''
yarnPath: .yarn/releases/yarn-3.5.0.cjs
supportedArchitectures:
  os:
    - 'darwin'
    - 'linux'
    - 'win32'
  cpu:
    - 'x64'
    - 'arm'
    - 'arm64'
  libc:
    - 'glibc'
    - 'musl'
