name: Bug Report
description: File a bug report
title: '[Bug] '
labels: ['type: bug']
body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: describe-the-bug
    attributes:
      label: Description of the bug
      description: Please describe in full detail, what happened and what you expected to happen instead. Feel free to add pictures if applicable.
    validations:
      required: true
  - type: textarea
    id: ways-to-reproduce
    attributes:
      label: How to reproduce
      description: If you remember, please add a description of what you did to reproduce the bug.
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: textarea
    id: cli-info
    attributes:
      label: Info output of dashdot cli
      description: If you are running docker, please execute `docker exec CONTAINER yarn cli info` and paste the output. If you are running from source, just execute `yarn cli info` and paste the output. This will be automatically formatted into code, so no need for backticks.
      render: shell
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
  - type: dropdown
    id: deployment
    attributes:
      label: Where is your instance running?
      multiple: true
      options:
        - Linux Server
        - Windows Server
        - Desktop PC (Windows)
        - Desktop PC (Linux)
        - Desktop PC (Mac OS)
        - Raspberry Pi
        - Other (Please specify below)
  - type: textarea
    id: extra
    attributes:
      label: Additional context
      description: If there is anything else you want to note?
