export const TEST_CASE_1 = {
  disks: [
    {
      device: '/dev/sda',
      type: 'HD',
      name: 'QEMU HARDDISK   ',
      vendor: 'QEMU',
      size: 429496729600,
      bytesPerSector: null,
      totalCylinders: null,
      totalHeads: null,
      totalSectors: null,
      totalTracks: null,
      tracksPerCylinder: null,
      sectorsPerTrack: null,
      firmwareRevision: '2.5+',
      serialNum: '',
      interfaceType: '',
      smartStatus: 'unknown',
      temperature: null,
    },
  ],
  sizes: [
    {
      fs: 'overlay',
      type: 'overlay',
      size: 429236563968,
      used: 185197596672,
      available: 244022190080,
      use: 43.15,
      mount: '/',
    },
    {
      fs: '/dev/sda1',
      type: 'ext4',
      size: 429236563968,
      used: 185197596672,
      available: 244022190080,
      use: 43.15,
      mount: '/mnt/host',
    },
    {
      fs: '/dev/sda15',
      type: 'vfat',
      size: 109422592,
      used: 5436416,
      available: 103986176,
      use: 4.97,
      mount: '/mnt/host/boot/efi',
    },
    {
      fs: '/dev/loop3',
      type: 'squashfs',
      size: 49283072,
      used: 49283072,
      available: 0,
      use: 100,
      mount: '/mnt/host/snap/snapd/16010',
    },
    {
      fs: '/dev/loop6',
      type: 'squashfs',
      size: 49283072,
      used: 49283072,
      available: 0,
      use: 100,
      mount: '/mnt/host/snap/snapd/16292',
    },
    {
      fs: '/dev/loop5',
      type: 'squashfs',
      size: 108134400,
      used: 108134400,
      available: 0,
      use: 100,
      mount: '/mnt/host/snap/lxd/23367',
    },
    {
      fs: '/dev/loop2',
      type: 'squashfs',
      size: 65011712,
      used: 65011712,
      available: 0,
      use: 100,
      mount: '/mnt/host/snap/core20/1593',
    },
    {
      fs: '/dev/loop4',
      type: 'squashfs',
      size: 65011712,
      used: 65011712,
      available: 0,
      use: 100,
      mount: '/mnt/host/snap/core20/1611',
    },
    {
      fs: '/dev/loop7',
      type: 'squashfs',
      size: 114032640,
      used: 114032640,
      available: 0,
      use: 100,
      mount: '/mnt/host/snap/lxd/23537',
    },
  ],
  blocks: [
    {
      name: 'sda',
      type: 'disk',
      fsType: '',
      mount: '',
      size: 429496729600,
      physical: 'HDD',
      uuid: '',
      label: '',
      model: 'QEMU HARDDISK   ',
      serial: '',
      removable: false,
      protocol: '',
      group: undefined,
    },
    {
      name: 'sda1',
      type: 'part',
      fsType: 'ext4',
      mount: '/mnt/host',
      size: 429380320768,
      physical: '',
      uuid: '43d2b5d9-3af2-48e8-908f-9b975e8974d6',
      label: 'cloudimg-rootfs',
      model: '',
      serial: '',
      removable: false,
      protocol: '',
      group: undefined,
    },
    {
      name: 'sda14',
      type: 'part',
      fsType: '',
      mount: '',
      size: 4194304,
      physical: '',
      uuid: '',
      label: '',
      model: '',
      serial: '',
      removable: false,
      protocol: '',
      group: undefined,
    },
    {
      name: 'sda15',
      type: 'part',
      fsType: 'vfat',
      mount: '/mnt/host/boot/efi',
      size: 111149056,
      physical: '',
      uuid: '9DDD-AECA',
      label: 'UEFI',
      model: '',
      serial: '',
      removable: false,
      protocol: '',
      group: undefined,
    },
    {
      name: 'sr0',
      type: 'rom',
      fsType: 'iso9660',
      mount: '',
      size: 4194304,
      physical: 'CD/DVD',
      uuid: '2021-12-31-15-47-20-00',
      label: 'cidata',
      model: 'QEMU DVD-ROM    ',
      serial: '',
      removable: true,
      protocol: 'ata',
      group: undefined,
    },
  ],
  layout: [{ device: 'sda', brand: 'QEMU', size: 429496729600, type: 'HD' }],
  output: { layout: [{ load: 185203033088 }] },
};

// https://github.com/MauriceNino/dashdot/issues/292
export const TEST_CASE_2 = {
  disks: [
    {
      device: '/dev/sda',
      type: 'SSD',
      name: 'KINGSTON SA400S3',
      vendor: 'Kingston Technology',
      size: 240057409536,
      bytesPerSector: null,
      totalCylinders: null,
      totalHeads: null,
      totalSectors: null,
      totalTracks: null,
      tracksPerCylinder: null,
      sectorsPerTrack: null,
      firmwareRevision: '0100',
      serialNum: '',
      interfaceType: 'SATA',
      smartStatus: 'unknown',
      temperature: null,
    },
    {
      device: '/dev/sdb',
      type: 'HD',
      name: 'WDC WD5000AAKX-6',
      vendor: 'Western Digital',
      size: 500107862016,
      bytesPerSector: null,
      totalCylinders: null,
      totalHeads: null,
      totalSectors: null,
      totalTracks: null,
      tracksPerCylinder: null,
      sectorsPerTrack: null,
      firmwareRevision: '1H18',
      serialNum: '',
      interfaceType: 'SATA',
      smartStatus: 'unknown',
      temperature: null,
    },
    {
      device: '/dev/sdc',
      type: 'HD',
      name: 'WDC WD10EZEX-08W',
      vendor: 'Western Digital',
      size: 1000204886016,
      bytesPerSector: null,
      totalCylinders: null,
      totalHeads: null,
      totalSectors: null,
      totalTracks: null,
      tracksPerCylinder: null,
      sectorsPerTrack: null,
      firmwareRevision: '1A02',
      serialNum: '',
      interfaceType: 'SATA',
      smartStatus: 'unknown',
      temperature: null,
    },
    {
      device: '/dev/sdd',
      type: 'HD',
      name: 'WDC WD5000AAKX-2',
      vendor: 'Western Digital',
      size: 500107862016,
      bytesPerSector: null,
      totalCylinders: null,
      totalHeads: null,
      totalSectors: null,
      totalTracks: null,
      tracksPerCylinder: null,
      sectorsPerTrack: null,
      firmwareRevision: '1H17',
      serialNum: '',
      interfaceType: 'SATA',
      smartStatus: 'unknown',
      temperature: null,
    },
  ],
  sizes: [
    {
      fs: 'overlay',
      type: 'overlay',
      size: 235148750848,
      used: 110298296320,
      available: 112830996480,
      use: 49.43,
      mount: '/',
    },
    {
      fs: '/dev/sda2',
      type: 'ext4',
      size: 235148750848,
      used: 110298296320,
      available: 112830996480,
      use: 49.43,
      mount: '/mnt/host',
    },
    {
      fs: '/dev/sdd1',
      type: 'ext4',
      size: 491110858752,
      used: 32112738304,
      available: 433976004608,
      use: 6.89,
      mount: '/mnt/host/mnt/200GB',
    },
    {
      fs: '/dev/loop1',
      type: 'squashfs',
      size: 58327040,
      used: 58327040,
      available: 0,
      use: 100,
      mount: '/mnt/host/snap/core18/2409',
    },
    {
      fs: '/dev/loop0',
      type: 'squashfs',
      size: 58327040,
      used: 58327040,
      available: 0,
      use: 100,
      mount: '/mnt/host/snap/core18/2538',
    },
    {
      fs: '/dev/loop2',
      type: 'squashfs',
      size: 65011712,
      used: 65011712,
      available: 0,
      use: 100,
      mount: '/mnt/host/snap/core20/1611',
    },
    {
      fs: '/dev/loop4',
      type: 'squashfs',
      size: 71172096,
      used: 71172096,
      available: 0,
      use: 100,
      mount: '/mnt/host/snap/lxd/22753',
    },
    {
      fs: '/dev/loop5',
      type: 'squashfs',
      size: 73793536,
      used: 73793536,
      available: 0,
      use: 100,
      mount: '/mnt/host/snap/lxd/21029',
    },
    {
      fs: '/dev/loop3',
      type: 'squashfs',
      size: 65011712,
      used: 65011712,
      available: 0,
      use: 100,
      mount: '/mnt/host/snap/core20/1593',
    },
    {
      fs: '/dev/loop7',
      type: 'squashfs',
      size: 49283072,
      used: 49283072,
      available: 0,
      use: 100,
      mount: '/mnt/host/snap/snapd/16010',
    },
    {
      fs: '/dev/loop6',
      type: 'squashfs',
      size: 49283072,
      used: 49283072,
      available: 0,
      use: 100,
      mount: '/mnt/host/snap/snapd/16292',
    },
    {
      fs: '/dev/sdb1',
      type: 'ext4',
      size: 491110858752,
      used: 331505643520,
      available: 134583099392,
      use: 71.13,
      mount: '/mnt/host/mnt/500GB_A',
    },
    {
      fs: '/dev/sdc1',
      type: 'ext4',
      size: 983358451712,
      used: 443730186240,
      available: 489601335296,
      use: 47.54,
      mount: '/mnt/host/mnt/1TB_A',
    },
  ],
  blocks: [
    {
      name: 'sda',
      type: 'disk',
      fsType: '',
      mount: '',
      size: 240057409536,
      physical: 'SSD',
      uuid: '',
      label: '',
      model: 'KINGSTON SA400S3',
      serial: '',
      removable: false,
      protocol: 'sata',
      group: undefined,
    },
    {
      name: 'sdb',
      type: 'disk',
      fsType: '',
      mount: '',
      size: 500107862016,
      physical: 'HDD',
      uuid: '',
      label: '',
      model: 'WDC WD5000AAKX-6',
      serial: '',
      removable: false,
      protocol: 'sata',
      group: undefined,
    },
    {
      name: 'sdc',
      type: 'disk',
      fsType: '',
      mount: '',
      size: 1000204886016,
      physical: 'HDD',
      uuid: '',
      label: '',
      model: 'WDC WD10EZEX-08W',
      serial: '',
      removable: false,
      protocol: 'sata',
      group: undefined,
    },
    {
      name: 'sdd',
      type: 'disk',
      fsType: '',
      mount: '',
      size: 500107862016,
      physical: 'HDD',
      uuid: '',
      label: '',
      model: 'WDC WD5000AAKX-2',
      serial: '',
      removable: false,
      protocol: 'sata',
      group: undefined,
    },
    {
      name: 'loop0',
      type: 'loop',
      fsType: 'squashfs',
      mount: '/mnt/host/snap/core18/2538',
      size: 58261504,
      physical: '',
      uuid: '',
      label: '',
      model: '',
      serial: '',
      removable: false,
      protocol: '',
      group: undefined,
    },
    {
      name: 'loop1',
      type: 'loop',
      fsType: 'squashfs',
      mount: '/mnt/host/snap/core18/2409',
      size: 58232832,
      physical: '',
      uuid: '',
      label: '',
      model: '',
      serial: '',
      removable: false,
      protocol: '',
      group: undefined,
    },
    {
      name: 'loop2',
      type: 'loop',
      fsType: 'squashfs',
      mount: '/mnt/host/snap/core20/1611',
      size: 64966656,
      physical: '',
      uuid: '',
      label: '',
      model: '',
      serial: '',
      removable: false,
      protocol: '',
      group: undefined,
    },
    {
      name: 'loop3',
      type: 'loop',
      fsType: 'squashfs',
      mount: '/mnt/host/snap/core20/1593',
      size: 64970752,
      physical: '',
      uuid: '',
      label: '',
      model: '',
      serial: '',
      removable: false,
      protocol: '',
      group: undefined,
    },
    {
      name: 'loop4',
      type: 'loop',
      fsType: 'squashfs',
      mount: '/mnt/host/snap/lxd/22753',
      size: 71106560,
      physical: '',
      uuid: '',
      label: '',
      model: '',
      serial: '',
      removable: false,
      protocol: '',
      group: undefined,
    },
    {
      name: 'loop5',
      type: 'loop',
      fsType: 'squashfs',
      mount: '/mnt/host/snap/lxd/21029',
      size: 73728000,
      physical: '',
      uuid: '',
      label: '',
      model: '',
      serial: '',
      removable: false,
      protocol: '',
      group: undefined,
    },
    {
      name: 'loop6',
      type: 'loop',
      fsType: 'squashfs',
      mount: '/mnt/host/snap/snapd/16292',
      size: 49242112,
      physical: '',
      uuid: '',
      label: '',
      model: '',
      serial: '',
      removable: false,
      protocol: '',
      group: undefined,
    },
    {
      name: 'loop7',
      type: 'loop',
      fsType: 'squashfs',
      mount: '/mnt/host/snap/snapd/16010',
      size: 49233920,
      physical: '',
      uuid: '',
      label: '',
      model: '',
      serial: '',
      removable: false,
      protocol: '',
      group: undefined,
    },
    {
      name: 'sda1',
      type: 'part',
      fsType: '',
      mount: '',
      size: 1048576,
      physical: '',
      uuid: '',
      label: '',
      model: '',
      serial: '',
      removable: false,
      protocol: '',
      group: undefined,
    },
    {
      name: 'sda2',
      type: 'part',
      fsType: 'ext4',
      mount: '/mnt/host',
      size: 240053649408,
      physical: '',
      uuid: '086b566c-905f-4ce4-b169-b2928891c753',
      label: '',
      model: '',
      serial: '',
      removable: false,
      protocol: '',
      group: undefined,
    },
    {
      name: 'sdb1',
      type: 'part',
      fsType: 'ext4',
      mount: '/mnt/host/mnt/500GB_A',
      size: 500106788864,
      physical: '',
      uuid: '4c28e3f5-70eb-49ca-8d98-e7f8479dc1ae',
      label: '',
      model: '',
      serial: '',
      removable: false,
      protocol: '',
      group: undefined,
    },
    {
      name: 'sdc1',
      type: 'part',
      fsType: 'ext4',
      mount: '/mnt/host/mnt/1TB_A',
      size: 1000203091968,
      physical: '',
      uuid: '360b4050-8777-4bd5-84ff-5cf7dc8601d5',
      label: '',
      model: '',
      serial: '',
      removable: false,
      protocol: '',
      group: undefined,
    },
    {
      name: 'sdd1',
      type: 'part',
      fsType: 'ext4',
      mount: '/mnt/host/mnt/500GB_B',
      size: 500106788864,
      physical: '',
      uuid: 'b5ec1270-073b-474a-8359-55a19964293f',
      label: '',
      model: '',
      serial: '',
      removable: false,
      protocol: '',
      group: undefined,
    },
  ],
  layout: [
    {
      brand: 'Kingston Technology',
      device: 'sda',
      size: 240057409536,
      type: 'SSD',
    },
    { brand: 'Western Digital', device: 'sdb', size: 500107862016, type: 'HD' },
    {
      brand: 'Western Digital',
      device: 'sdc',
      size: 1000204886016,
      type: 'HD',
    },
    { brand: 'Western Digital', device: 'sdd', size: 500107862016, type: 'HD' },
  ],
  output: {
    layout: [
      { load: 110298296320 },
      { load: 331505643520 },
      { load: 443730186240 },
      { load: 0 },
    ],
  },
};
