"use client"

import {
  Cpu,
  Github,
  Layout,
  Monitor,
  ShieldCheck,
} from 'lucide-react';
import Image from 'next/image';
import { twMerge } from 'tailwind-merge';
import { CopyToClipboard } from '@/components/copy-to-clipboard';
import { useMountedTheme } from '@/hooks/useMountedTheme';

const DOCKER_COMMAND =
  'docker container run -it -p 80:3001 -v /:/mnt/host:ro --privileged mauricenino/dashdot';

// Disclaimer: This page (and only this page!) is 90% generated by AI, with some manual tweaks.
// I simply don't care too much about maintainability of the homepage, as long as it looks good and gets the point across.
// If you want to make changes, just edit the JSX directly and don't worry about the code quality here :)
export default function HomePage() {
  const theme = useMountedTheme();

  return (
    <>
      <header className="relative pt-32 pb-16 overflow-hidden">
        {/* Ambient Background Glow */}
        <div
          className={twMerge(
            'absolute top-0 left-1/2 -translate-x-1/2 w-[90%] h-[80%] blur-[120px] rounded-full -z-10',
            theme === 'light' ? 'bg-purple-300/20' : 'bg-purple-600/20',
          )}
        />

        <div className="max-w-7xl mx-auto px-6 text-center">
          <h1
            className={twMerge(
              'text-5xl md:text-8xl font-extrabold tracking-tighter mb-6 bg-linear-to-b bg-clip-text text-transparent pb-2',
              theme === 'light'
                ? 'from-black to-gray-400'
                : 'from-white to-gray-500',
            )}
          >
            Your server, <br className="hidden md:block" /> at a glance.
          </h1>

          <p
            className={twMerge(
              'max-w-2xl mx-auto text-lg md:text-xl mb-10 leading-relaxed',
              theme === 'light' ? 'text-gray-600' : 'text-gray-400',
            )}
          >
            The simplest way to monitor your one-node setup. Beautiful,
            lightweight, and easy to get going.
          </p>

          <CopyToClipboard text={DOCKER_COMMAND} />
        </div>
      </header>

      {/* Main Application Showcase */}
      <section className="max-w-6xl mx-auto w-full px-6 pb-24">
        <div className="relative">
          {/* Subtle glow behind the image */}
          <div
            className={twMerge(
              'absolute -inset-10 blur-[100px] rounded-full -z-10 opacity-50',
              theme === 'light' ? 'bg-purple-400/70' : 'bg-purple-600/20',
            )}
          />

          {/* Browser Frame */}
          <div className="rounded-2xl overflow-hidden transform hover:-translate-y-1 transition-transform duration-500 border">
            {/* Browser Header */}
            <div
              className={twMerge(
                'px-4 py-3 flex items-center gap-4 border-b',
                theme === 'light'
                  ? 'bg-gray-100 border-gray-300'
                  : 'bg-[#1A1A1A] border-white/5',
              )}
            >
              <div className="flex gap-1.5">
                <div className="w-3 h-3 rounded-full bg-red-500/20 border border-red-500/40" />
                <div className="w-3 h-3 rounded-full bg-yellow-500/20 border border-yellow-500/40" />
                <div className="w-3 h-3 rounded-full bg-green-500/20 border border-green-500/40" />
              </div>
              <div
                className={twMerge(
                  'flex-1 max-w-md mx-auto h-6 rounded-md flex items-center justify-center border',
                  theme === 'light'
                    ? 'bg-gray-200/70 border-gray-300'
                    : 'bg-black/40 border-white/5',
                )}
              >
                <span
                  className={twMerge(
                    'text-[10px] font-mono tracking-tight',
                    theme === 'light' ? 'text-gray-500' : 'text-gray-500',
                  )}
                >
                  https://dash.mauz.dev
                </span>
              </div>
            </div>

            {/* Application Screenshot Placeholder */}
            <a
              href="https://dash.mauz.dev"
              className="block relative bg-[#050505] aspect-video w-full overflow-hidden group"
            >
              <Image
                src={
                  theme === 'light'
                    ? '/img/screenshot_lightmode.png'
                    : '/img/screenshot_darkmode.png'
                }
                alt="Dashdot Dashboard Preview"
                className="w-full h-full object-cover opacity-90 group-hover:opacity-100 transition-opacity duration-700"
                fill
              />

              {/* Overlay on hover */}
              <div className="absolute inset-0 bg-black/40 opacity-0 group-hover:opacity-100 transition-opacity flex items-center justify-center">
                <div className="px-6 py-3 bg-white text-black font-bold rounded-full flex items-center gap-2">
                  <Monitor size={18} /> View Demo Dashboard
                </div>
              </div>
            </a>
          </div>
        </div>
      </section>

      {/* Feature Grid */}
      <section
        id="features"
        className={twMerge(
          'py-24',
          theme === 'light' ? 'bg-gray-50' : 'bg-[#0D0D0D]',
        )}
      >
        <div className="max-w-7xl mx-auto px-6">
          <div className="grid md:grid-cols-3 gap-16">
            <div className="space-y-4">
              <div
                className={twMerge(
                  'w-12 h-12 rounded-xl flex items-center justify-center border',
                  theme === 'light'
                    ? 'bg-purple-100 border-purple-200 text-purple-700'
                    : 'bg-purple-500/10 border-purple-500/20 text-purple-400',
                )}
              >
                <Layout size={24} />
              </div>
              <h3 className="text-xl font-bold">Glassmorphic Design</h3>
              <p
                className={twMerge(
                  'leading-relaxed',
                  theme === 'light' ? 'text-gray-600' : 'text-gray-400',
                )}
              >
                Modern UI with dynamic backgrounds and smooth animations.
                Monitoring has never looked this good.
              </p>
            </div>

            <div className="space-y-4">
              <div
                className={twMerge(
                  'w-12 h-12 rounded-xl flex items-center justify-center border',
                  theme === 'light'
                    ? 'bg-blue-100 border-blue-200 text-blue-700'
                    : 'bg-blue-500/10 border-blue-500/20 text-blue-400',
                )}
              >
                <Cpu size={24} />
              </div>
              <h3 className="text-xl font-bold">High Performance</h3>
              <p
                className={twMerge(
                  'leading-relaxed',
                  theme === 'light' ? 'text-gray-600' : 'text-gray-400',
                )}
              >
                Written in React and Node.js with a focus on responsiveness.
                Get real-time insights without any lag, even on low-end hardware.
              </p>
            </div>

            <div className="space-y-4">
              <div
                className={twMerge(
                  'w-12 h-12 rounded-xl flex items-center justify-center border',
                  theme === 'light'
                    ? 'bg-green-100 border-green-200 text-green-700'
                    : 'bg-green-500/10 border-green-500/20 text-green-400',
                )}
              >
                <ShieldCheck size={24} />
              </div>
              <h3 className="text-xl font-bold">Privacy First</h3>
              <p
                className={twMerge(
                  'leading-relaxed',
                  theme === 'light' ? 'text-gray-600' : 'text-gray-400',
                )}
              >
                Everything stays on your machine. Dashdot doesn't send data
                anywhere and works fully offline.
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* Technical Specs Table */}
      <section className="py-24 max-w-4xl mx-auto w-full px-6">
        <div className="text-center mb-12">
          <h2 className="text-2xl font-bold mb-2">Technical Details</h2>
          <p
            className={twMerge(
              theme === 'light' ? 'text-gray-600' : 'text-gray-400',
            )}
          >
            Perfect for your Raspberry Pi or small VPS.
          </p>
        </div>
        <div
          className={twMerge(
            'rounded-2xl overflow-hidden border',
            theme === 'light'
              ? 'bg-white border-gray-200 shadow-xl'
              : 'bg-[#111] border-white/10 shadow-2xl',
          )}
        >
          <div
            className={twMerge(
              'font-mono text-sm',
              theme === 'light'
                ? 'divide-y divide-gray-300'
                : 'divide-y divide-white/5',
            )}
          >
            {[
              { label: 'Docker Image Size', value: '~210 MB' },
              { label: 'Architectures', value: 'x86, ARM64' },
              { label: 'Supported Systems', value: 'Linux, MacOS, Windows' },
              { label: 'Tech Stack', value: 'React, Node.js, Express' },
            ].map((spec) => (
              <div
                key={spec.label}
                className={twMerge(
                  'px-8 py-5 flex justify-between group hover:bg-white/2 transition-colors',
                  theme === 'light' ? '' : '',
                )}
              >
                <span
                  className={twMerge(
                    theme === 'light' ? 'text-gray-600' : 'text-gray-400',
                  )}
                >
                  {spec.label}
                </span>
                <span
                  className={twMerge(
                    'font-bold',
                    theme === 'light' ? 'text-gray-900' : 'text-white',
                  )}
                >
                  {spec.value}
                </span>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Footer */}
      <footer
        className={twMerge(
          'py-20 border-t',
          theme === 'light' ? 'border-gray-200' : 'border-white/10',
        )}
      >
        <div className="max-w-7xl mx-auto px-6 flex flex-col md:flex-row justify-between items-center gap-8">
          <div className="flex items-center gap-4">
            <Image
              src="/img/logo512.png"
              alt="Dashdot Logo"
              width={32}
              height={32}
            />
            <span className="text-xl font-bold tracking-tight">Dash.</span>
          </div>

          <div
            className={twMerge(
              'text-center text-[10px] tracking-widest uppercase',
              theme === 'light' ? 'text-gray-400' : 'text-gray-600',
            )}
          >
            Proudly open source • MIT License
          </div>

          <div className="flex items-center gap-4">
            <a
              href="https://github.com/mauricenino/dashdot"
              className={twMerge(
                'bg-white/5 hover:bg-white/10 p-2.5 rounded-full border transition-all',
                theme === 'light'
                  ? 'border-gray-200 text-gray-400 hover:text-black'
                  : 'border-white/10 text-gray-400 hover:text-white',
              )}
            >
              <Github size={20} />
            </a>
            <a
              href="/docs/installation/docker"
              className="bg-purple-600 hover:bg-purple-500 text-white font-bold px-8 py-2.5 rounded-full transition-all shadow-lg shadow-purple-600/20"
            >
              Get Started
            </a>
          </div>
        </div>
      </footer>
    </>
  );
}
