name: Test & Deploy Dev

on:
  push:
    branches: ['dev', 'feature/**', 'renovate/**']
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # SETUP
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/login-action@v2
        with:
          username: mauricenino
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # TEST
      - name: install dependencies
        if: ${{ github.event_name != 'pull_request' }}
        run: yarn --immutable --immutable-cache
      - name: install dependencies (pr)
        if: ${{ github.event_name == 'pull_request' }}
        run: yarn --immutable --immutable-cache --check-cache
      - name: test
        run: yarn test

      # DEPLOY
      - name: build and push
        uses: docker/build-push-action@v3
        with:
          platforms: linux/amd64
          target: prod
          push: ${{ github.event_name != 'pull_request' && github.ref == 'refs/heads/dev' }}
          build-args: |
            VERSION=0.0.0-dev
            BUILDHASH=${{ github.sha }}
          labels: |
            org.opencontainers.image.title="dash."
            org.opencontainers.image.description="dash. - a modern server dashboard"
            org.opencontainers.image.authors="MauriceNino <mauriceprivat98@gmail.com>"
            org.opencontainers.image.url=https://github.com/MauriceNino/dashdot
            org.opencontainers.image.source=https://github.com/MauriceNino/dashdot
            org.opencontainers.image.licenses=MIT
          tags: |
            mauricenino/dashdot:dev
            ghcr.io/mauricenino/dashdot:dev
          cache-from: type=gha
          cache-to: type=gha,mode=max
