name: Docker Image CI

on:
  push:
    tags:
      - "v*.*"
      
env:
  IMAGE_NAME: dashdotzhcn

jobs:
  get-tags:
    runs-on: ubuntu-latest

    outputs:
      tags: ${{ steps.set-output-id.outputs.tags }}

    steps:
      - uses: actions/checkout@v3
      - name: set-output
        id: set-output-id
        run: |
          VERSION=edge
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/v}
          fi
          echo ::set-output name=tags::${VERSION}
          
  push-docker-pkg-github:
    runs-on: ubuntu-latest

    env:
      REGISTRY: docker.pkg.github.com
      OWNER: '${{ github.repository_owner }}'

    steps:
      - name: set lower case owner name
        run: |
          echo "OWNER_LC=${OWNER,,}" >>${GITHUB_ENV}
      - uses: actions/checkout@v3
      - name: Login
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.PACKAGES_TOKEN }}
      - name: Build && Push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ OWNER_LC }}/${{ env.IMAGE_NAME }}:latest
